RocketCommunicationsInc/astro

packages/web-components/src/stories/astro-uxds/welcome/javascript.stories.mdx
Changes a link in the cdn to the correct url. 
https://rocketcom.atlassian.net/browse/ASTRO-2088
CDN didn't work before due to wrong link.
=> Astro 2088 js docs

packages/web-components/src/components/rux-clock/rux-clock.scss
Clock got a design update in Figma: https://www.figma.com/file/ZtHeSWpISd8hJjN46uY9pm/Astro-UX-Design-System?node-id=5314%3A130533
This updates clock styles.
https://rocketcom.atlassian.net/browse/ASTRO-2047
Removes the `border-right: none` on  date, adds background to sublabel, removes margin on date/time so sublabel is now flush with it. Removes the margin-left on aos so that aos/los are flush as well. Adds a 3.938rem (63px) height for clock component. 
Updates clock styles to match Figma.
=> Astro 2047 clock style update

packages/web-components/src/components.d.ts, packages/web-components/src/components/rux-classification-marking/rux-classification-marking.tsx, packages/web-components/src/components/rux-classification-marking/test/rux-classification-marking.spec.tsx, packages/web-components/src/stories/classification-marking.stories.mdx
In SB, default classification marking read `Select a classification marking`. This changes the SB so that it defaults to `unclassfied` correctly.
https://rocketcom.atlassian.net/browse/ASTRO-1826
Removed the args declarations in SB. Because `args.classification` was undefined it was hitting the text fallback in rux-classification-banner. 
The text fallback (line 71 in .tsx) simply changes the label to be `Select a classification marking` if the classification passed in isn't valid.
Makes the default banner in SB correct.
=> Astro 1826 classification default

packages/web-components/src/stories/astro-uxds/welcome/StartHere.stories.mdx
adds code sandbox links to starter kits
[ASTRO-2198](https://rocketcom.atlassian.net/browse/ASTRO-2198)
I really need a quick way to spin up astro in all three frameworks when Im debugging.
* svelte starter when imported to codesandbox, doesnt work for whatever reason https://codesandbox.io/s/broken-worker-c1vzh
* angular/html dont have official starter kit repos yet so I just added them in codesandbox. theyll be replaced eventually. 
* the link placement is a little confusing because the whole list element is an anchor, but you have a link inside that as well.
=> feat: sandbox starters

packages/angular/package.json, packages/angular/src/directives/text-value-accessor.ts, packages/web-components/wrapper-bindings/angular.bindings.ts
adds missing value accessors for select and slider so they can be used in forms
removes single radio accessor since its not supposed to be used outside a radio group and also blur was not the right event
[ASTRO-2232](https://rocketcom.atlassian.net/browse/ASTRO-2232)
so we can use these components in forms
=> Astro 2232 missing value accessors

.github/workflows/publish.yml, .github/workflows/pull-request.yml, README.md
Added a workflow to allow packages to be published concurrently with the push of a button through the workflow interface.
With this workflow we'll be able to publish the current state of the repo with a single button push.
=> ci(release): added github workflow to manage releases

packages/web-components/src/stories/astro-uxds/welcome/angular.stories.mdx, packages/web-components/src/stories/astro-uxds/welcome/react.stories.mdx
Adds npx command documentation to react and angular storybook.
This should probably not be merged until we publish the `@astrouxds/react-starter` and `@astrouxds/angular-starter` packages.
https://rocketcom.atlassian.net/browse/ASTRO-2256
Adds docs and awareness of npx commands for react and angular starter kits
=> docs(stories): added documentation for react and angular npx

packages/web-components/src/stories/astro-sandboxes/forms/svelte/basic/Form.svelte
Noticed when I was added labels to options in the react form that the svelte sandbox creates a 405 page on submit. I added in a handlesubmit function that displays the values in an alert when submitted. 
https://rocketcom.atlassian.net/browse/ASTRO-2360
Allows for submit on svelte form. 
The rux-select in the basic svelte form example looks empty. While I was adding the submit function, it filled itself with no change from me so I'll check after this is merged. Happy Halloween, I guess
=> Astro 2360 svelte form submit

packages/react/package-lock.json, packages/react/package.json, packages/web-components/package-lock.json, packages/web-components/src/components.d.ts, packages/web-components/src/components/rux-icon/readme.md, packages/web-components/src/components/rux-modal/readme.md, packages/web-components/src/components/rux-modal/rux-modal.tsx
Removes the required props and validate function from rux-modal.
Updates jest version in packages/react so I could run tests.
https://rocketcom.atlassian.net/browse/ASTRO-2365
This will allow for the react tests to pass without the console error around modal-title and modal-message being required. 
There isn't a reason for these to be required any more, and rux-modal will be going through a refactor soon anyway, see: https://rocketcom.atlassian.net/browse/ASTRO-2063
=> refactor(web-components): removed required props and validate function

packages/astro-uxds/_content/components/classification-markings.md
Forgot in my last pr that the alt text for images is used for captions.
Removed the blank placeholder alt text to get rid of the unnecessary caption.
(none - quick fix)
Resolves an error I caused in my last PR
=> docs(astro-uxds): fix class markings caption

packages/astro-uxds/_content/components/sign-in.md
Points to the correct SB demo in astrouxds for sign-in 
https://rocketcom.atlassian.net/browse/ASTRO-2307
Changed the dmeo and storybook front matter on sign-in.md, added scrolling: yes to enable scrolling
Sign in pattern now shows correctly on UXDS
=> fix(astro-uxds): sign in now points to the correct SB example, enabled scrolling

packages/astro-uxds/_content/components/pop-up.md, packages/web-components/src/components/rux-pop-up-menu/rux-pop-up-menu.tsx, packages/web-components/src/stories/popup.stories.mdx
Changed the pop-up default SB to be closed by default. Added a span that notifies user to click icon to see pop-up.
Bumped the demo SB size on the pop-up section of astrouxds 50px to prevent the pop-up from rendering above the icon and out of view.
https://rocketcom.atlassian.net/browse/ASTRO-2400
The issue with pop-up appearing in the wrong place when set to open by default remains, but now it won't be a problem in our SB
Pop-up was open by default on SB, and that made it appear in the wrong location 
Does not fix core issue with incorrect loading when open by default, but does fix our SB.
=> Astro 2400 pop up uxds

packages/web-components/src/components/rux-notification/rux-notification.tsx, packages/web-components/src/components/rux-notification/test/index.html, packages/web-components/src/components/rux-notification/test/rux-notification.e2e.js, packages/web-components/src/components/rux-tree-node/rux-tree-node.tsx
fixes issue where close icon was not properly closing Notification
[ASTRO-2476](https://rocketcom.atlassian.net/browse/ASTRO-2476)
a recent change removed arrow functions from a lot of components due to this eslint rule https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md
this ended up breaking notification, which was intentionally relying on that rerender.
added some test coverage
=> Astro 2476 hotfix notification closing

packages/web-components/src/components/rux-notification/rux-notification.scss, packages/web-components/src/components/rux-notification/rux-notification.tsx, packages/web-components/src/components/rux-notification/test/rux-notification.spec.tsx
notification - replaces open attribute styling with a class
[ASTRO-2476](https://rocketcom.atlassian.net/browse/ASTRO-2476)
Because we were styling [open], the banner could never be closed in React or if the developer was passing in false `<rux-notification open="false">` because open would still exist. 
But notification is also weird in that we're applying a lot of styling to the host, which means the developer could be override that with `rux-notification { position: relative; }` and this is probably more common because that's currently the only way to control the positioning. 
So for backwards compatibility, we need to apply a class instead. But applying a class to the host element is an anti pattern--the developer could override that. To make sure that doesnt happen unknowingly, I …
=> fix(notification): can now be closed properly in react

packages/web-components/package-lock.json, packages/web-components/package.json
the output targets should be dev dependencies since they're only run on build 
https://github.com/ionic-team/stencil-ds-output-targets/blob/master/packages/example-project/component-library/package.json
- [x?] Bug fix
=> chore(web-components): move output targets to devDeps

packages/web-components/package-lock.json, packages/web-components/package.json
just bumps the storybook docs addon that fixes a minor deprecation in the new storybook
=> chore(web-components): bump storybook docs addon

packages/starter-kits/react-starter/README.md, packages/starter-kits/react-starter/public/index.html, packages/web-components/src/stories/astro-uxds/welcome/react.stories.mdx
Adds the roboto font info to the react getting started and adds it to the `index.html` file in react-starter. 
https://rocketcom.atlassian.net/browse/ASTRO-2501
Roboto font info was missing in the getting started for react SB and in the react-starter.
=> Astro 2501 react font

package.json, packages/web-components/cypress/support/index.js, packages/web-components/src/components/rux-clock/rux-clock.tsx, packages/web-components/src/components/rux-clock/test/__snapshots__/rux-clock.spec.tsx.snap, packages/web-components/src/components/rux-clock/test/index.html, packages/web-components/src/components/rux-clock/test/rux-clock.spec.tsx
This fixes a few issues with the AOS/LOS timestamps and timezones. When
changing the timezone, the AOS/LOS timestamps now update correctly to
show the selected timezone.
[ASTRO-2500](https://rocketcom.atlassian.net/browse/ASTRO-2500)
Clock tests now use Jest snapshots over `assertHTMLEquals` which was really annoying to maintain. We should probably move all tests to uses snapshots at some point. I feel like they might be slightly less readable though. 
Something really weird is going on in the tests. If I pass in strings as AOS/LOS timestamps, I get a totally unexpected output. `utcToZonedTime` returns '1988-04-22T15:12:12.000Z' in the test and returns '1988-04-22 09:12:12' in the browser. Created a separate ticket to look into this more. It behaves as expected in the browser. I suspect …
=> Astro 2500 rux clock bugs

packages/react/package-lock.json, packages/react/package.json
moves jest deps into devDeps. 
I wasn't getting the npm error mentioned in this [this issue](https://github.com/RocketCommunicationsInc/astro/issues/132#issuecomment-982054201) before moving jest to devDeps either. I built the react wrapper, symlinked and added it to a fresh CRA repo and it worked just fine, didn't even have to SKIP_PREFLIGHT_CHECK, so maybe this fixed that
https://rocketcom.atlassian.net/browse/ASTRO-2502
https://github.com/RocketCommunicationsInc/astro/issues/132#issue-1066528291
Users getting npm errors when using our React wrapped components.
=> chore(react): moved jest to dev dep

packages/web-components/src/components/rux-clock/rux-clock.tsx, packages/web-components/src/components/rux-clock/test/__snapshots__/rux-clock.spec.tsx.snap, packages/web-components/src/components/rux-clock/test/rux-clock.spec.tsx, packages/web-components/src/stories/clock.stories.mdx
The day of the year was being calculated based off the user's local timezone instead of the timezone that the clock was set to. 
Adds a note to the docs about the recommended format for timestamps 
ASTRO-2512
[#138](https://github.com/RocketCommunicationsInc/astro/issues/138)
Technically, we shouldn't need to explicitly set the timezone anywhere. Clock should return the same output given any local timezone. The exception is when using strings without timezones or unix timestamps as aos/los timestamps. We may want to think about deprecating those in favor of just '1988-04-22T12:12:12.000Z'.
Snapshots were updated to use 2021 as the mock date so that we can properly check for leap years.
=> fix(rux-clock): date is calculated off clock tz

.npmrc
removes .npmrc as we are no longer using it and it is causing errors in the changeset action
=> build: rm npmrc

.github/workflows/release.yml
bumps the version of node to 16 on the changeset action. when it goes to update the PR, it triggers the git hook to run our tests and that fails because stencil requires node 16
=> build: bump node version

packages/astro-uxds/_includes/_footer.njk
Comments out the failing widget in footer.js, line 51
This was causing the site to not be interactive without a refresh.
https://rocketcom.atlassian.net/browse/ASTRO-2352
Pretty sure that the data-id token has expired, thus the failing widget 
Fixes broken links on mobile.
=> fix(astro-uxds): commented out failing widget

.changeset/silly-pans-pull.md, packages/angular/src/directives/proxies.ts, packages/web-components/src/common/functional-components/MonitoringBadge/MonitoringBadge.tsx, packages/web-components/src/common/functional-components/MonitoringLabel.tsx, packages/web-components/src/components/rux-monitoring-icon/readme.md, packages/web-components/src/components/rux-monitoring-icon/rux-monitoring-icon.tsx, packages/web-components/src/components/rux-monitoring-icon/test/rux-monitoring-icon.spec.tsx, packages/web-components/src/components/rux-monitoring-progress-icon/readme.md, packages/web-components/src/components/rux-monitoring-progress-icon/rux-monitoring-progress-icon.tsx, packages/web-components/src/components/rux-monitoring-progress-icon/test/rux-monitoring-progress-icon.spec.tsx
Adds shadow parts for rux-monitoring-progress-icon
ASTRO-2608
rux-monitoring-icon also needed to be updated because it uses the same functional components for badge and label.
=> Astro 2608 shadow parts

.changeset/witty-dolls-cover.md, packages/web-components/src/components/rux-classification-marking/readme.md, packages/web-components/src/components/rux-classification-marking/rux-classification-marking.tsx, packages/web-components/src/components/rux-classification-marking/test/__snapshots__/rux-classification-marking.spec.tsx.snap
Adds a tag, header and footer shadow part to rux-classification-marking
https://rocketcom.atlassian.net/browse/ASTRO-2635
Classification markings contains two main divs, the normal banner/tag and the footer banner (which cannot be a tag). The footer already has a shadow part named footer-banner
shadow part effort
=> feat(classification-markings): tag, header and footer shadow part

.changeset/nine-owls-burn.md, .github/workflows/pull-request.yml, packages/web-components/src/components/rux-clock/readme.md, packages/web-components/src/components/rux-clock/rux-clock.tsx, packages/web-components/src/components/rux-clock/test/__snapshots__/rux-clock.spec.tsx.snap
Adds the shadow parts time, time-label, date, date-label, aos, aos-label, los and los-label. 
I think we'd have to move some css around to get away with having a part that encapuslates each section and the corresponding label, ie just the time part being moved up a div level. That is what I tried first, but the component styling takes place one level down from the first, thus the part wouldn't do anything to attributes that where already styled. 
I also removed two classes from clock that weren't being used: `rux-clock__day-of-the-year` and `rux-clock__time`. If i'm just blind and missed where they are being used let me know
https://rocketcom.atlassian.net/browse/ASTRO-2636
Adds shadow parts to rux-clock
=> Astro 2636 clock parts

.changeset/curvy-pans-develop.md, packages/web-components/src/components/rux-icon/readme.md, packages/web-components/src/components/rux-icon/rux-icon.tsx, packages/web-components/src/components/rux-icon/test/__snapshots__/rux-icon.spec.tsx.snap
Adds an `icon` shadow part to rux-icon's host. 
This will allow us to remove any icon shadow parts on other components that use rux icon
=> Rux icon part

.changeset/little-poems-stare.md, .changeset/short-items-joke.md, packages/web-components/src/components/rux-global-status-bar/readme.md, packages/web-components/src/components/rux-global-status-bar/rux-global-status-bar.tsx, packages/web-components/src/components/rux-global-status-bar/test/__snapshots__/rux-global-status-bar.spec.tsx.snap
Adds a `container` part to global status bar. 
It's added to header, because adding it to host had no effect when attempting to style with it. The rest of GSB is basically slots, which are customizable already.
https://rocketcom.atlassian.net/browse/ASTRO-2637
shadow parts boi
=> Astro 2637 gsb parts

.changeset/lucky-ears-try.md, packages/web-components/src/components/rux-pop-up-menu/rux-pop-up-menu.tsx, packages/web-components/src/components/rux-pop-up-menu/test/__snapshots__/rux-pop-up-menu.spec.tsx.snap
Adds a container shadow part to pop-up-menu's ul. 
https://rocketcom.atlassian.net/browse/ASTRO-2639
shadow part PI
=> Astro 2639 pop up parts

packages/web-components/src/stories/astro-uxds/welcome/StartHere.stories.mdx
sandbox links for vue/svelte in storybook weren't opening in new windows
=> docs: sandbox links open new window

packages/starter-kits/svelte-starter/index.js, packages/starter-kits/vue3-starter/src/main.js, packages/web-components/src/stories/astro-uxds/welcome/svelte.stories.mdx, packages/web-components/src/stories/astro-uxds/welcome/vue2.stories.mdx, packages/web-components/src/stories/astro-uxds/welcome/vue3.stories.mdx
svelte/vue docs/starter kits were using the custom-elements build that we'll be deprecating soon. there were also some rando typos using /build
=> Fix importing docs

packages/react/tsconfig.json
Sets `source-maps: false` in the `ts.config` of `/react` due to the source maps not working properly and producing a warning.
https://rocketcom.atlassian.net/browse/ASTRO-2777
Gets rid of a massive error when using `@astrouxds/react` 
Source maps are now disabled
=> chore(react): turned off source maps due to warning in react

.changeset/silver-radios-visit.md, packages/web-components/src/components/rux-clock/rux-clock.tsx, packages/web-components/src/components/rux-clock/test/__snapshots__/rux-clock.spec.tsx.snap
Date now displays ` {this.dayOfYear.toString().padStart(3, '0')}` so that the julien date is always 3 digits, padded with leading zeros. 
Updated snapshots.
A following PR will be made with the same change to the lit repo. 
https://rocketcom.atlassian.net/browse/ASTRO-2871
https://github.com/RocketCommunicationsInc/astro-components/issues/186
Fixes julien date in rux-clock to always be 3 digits.
=> fix(clock): Astro 2871 3-digit julien date

packages/starter-kits/react-starter/package-lock.json, packages/starter-kits/react-starter/package.json
Jump bumps the react starter kit to use the latest (6.1.0) version of astrouxds/react
=> chore(starter-kits): updated react-starter astro/react version

.changeset/cuddly-lemons-behave.md, packages/web-components/src/components/rux-classification-marking/rux-classification-marking.scss
Small changes that came out of the audit. 
Updated tag padding to be 10px 3px (in rem's tho) and removed line-height in order to get the height correct (is 22px in figma)
https://rocketcom.atlassian.net/browse/ASTRO-2924
Found during audit
=> style(class-markings): removed line-height from tag, updated padding

.changeset/cool-bananas-impress.md, packages/web-components/src/components/rux-clock/rux-clock.scss, packages/web-components/src/stories/clock.stories.mdx
Adds an `Other Variants` story to clock that shows the remaining controls/props (hide-labels, hide-date, and hide-timezone). 
Bumps the margin-left on AOS from 16px to 17px as per Figma 
https://rocketcom.atlassian.net/browse/ASTRO-2914
All clock variants are now represented, clock better matches design.
=> Astro 2914 clock variants

.changeset/old-buckets-teach.md, packages/web-components/src/components/rux-button/rux-button.scss
Updates secondary button to have correct text color on hover and when pressed. 
Adds `::slotted(rux-icon)` to instances of `rux-icon` styling to ensure correct colors. 
https://rocketcom.atlassian.net/browse/ASTRO-2984
Regressions failed where expected and have since had the references updated with the new additions. 
Secondary button now matches figma.
=> style(button): added hover color to secondary text, slotted icon styling

packages/web-components/src/components/rux-global-status-bar/readme.md, packages/web-components/src/components/rux-global-status-bar/rux-global-status-bar.tsx
username was listed as a slot, is not a slot, no longer listed as slot, slot has gone away. slot.
won't need a changeset.
https://rocketcom.atlassian.net/browse/ASTRO-2934
came from audit
=> Astro 2934 gsb docs update

.changeset/old-rats-join.md, packages/web-components/src/components/rux-push-button/rux-push-button.scss, packages/web-components/src/index.html, packages/web-components/src/stories/push-button.stories.mdx
Adds hover state styling and updates padding on push button. 
Adds icon and icon only variants to all variants page. 
Adds all of push-buttons props to the default story so the controls work now.
Hover/Variants - > https://rocketcom.atlassian.net/browse/ASTRO-2969
Padding -> https://rocketcom.atlassian.net/browse/ASTRO-2970
Adds hover styling, updated padding and variants to match Figma
=> Astro 2969 push btn audit

packages/web-components/src/components/rux-progress/rux-progress.scss, packages/web-components/src/global/tokens/_tokens.scss, packages/web-components/src/stories/progress.stories.mdx
Updates the display of progress depending on if it's indeterminate - (flex for regular, inline-block for spinner)
Updates padding on spinner to be 20px all around as it is in Figma
Updates padding of progress bar to 2px all around as it is in Figma
Removes controls from spinner story, as they aren't necessary. 
Figma has 
```
Radius
- The progress background is a fixed radius of 10 px.
- THe progress foreground is a fixed radius of 8 px. 
```
In dev we have tokens for: 
```
--progress-radius-outer: 9px;
--progress-radius-inner: 8px;
```
This is a change that we can wait on for tokens to be refreshed, I think .
I ran regressions, and since the padding changed to 2px on all progress bars, they all failed. They're just a pixel off by the looks of it. I will update regressions once this is …
=> Astro 2967 progress padding

.changeset/ten-panthers-provide.md, packages/web-components/src/components/rux-status/rux-status.scss
Changes the height and width of rux-status to be 12 px like figma (down from 1rem) 
Also updates the background positions style to match the new 12px base. 
https://rocketcom.atlassian.net/browse/ASTRO-2961
Dev -> Design audit
If you change the height/width of a rux-status, you'll have some bleed through of the other statuses since we're just changing the background image position of a single image. This was the case with the 1rem based size rux-status as well, so if we want this to be changed we should move to having each status symbol be a separate svg.
=> style(status): updated size to match figma, updated bg positions

.changeset/tasty-spiders-check.md, packages/web-components/src/components/rux-monitoring-icon/rux-monitoring-icon.scss
Updates the min height/width as per figma design.
Regressions fail due to the status icon size change previously implemented. Ticket out to update the critical size status icon when we get the svg's.
https://rocketcom.atlassian.net/browse/ASTRO-2956
Dev -> Design audit
=> Astro 2956 monitoring icon

packages/web-components/src/components/rux-switch/readme.md, packages/web-components/src/components/rux-switch/rux-switch.scss
Adds `white-space: nowrap` to rux-switch in order for labels with spaces to be rendered correctly.
Adds a `Listening to events` blurb in the readme that mentions using the ruxchange event to listen for the value of switch's `checked` attribute.
https://rocketcom.atlassian.net/browse/ASTRO-3112 -> label spaces
https://rocketcom.atlassian.net/browse/ASTRO-3115 -> checked issue
onClick is not the correct event to listen for since it fires twice - ruxchange contains the correct checked value. Listening to onclick was the reason the checked value seemed backwards. 
Label can now use spaces, docs updated to accommodate correct event listening
=> Astro 3115 switch checked

.changeset/curly-eggs-drum.md, packages/web-components/src/components/rux-switch/rux-switch.scss, packages/web-components/src/stories/switch.stories.mdx
Updates the hover state of switch's thumb and adds `on` and `with label` variants to SB.
Updating regressions references, will push this to main since it's just a hover state and story addition change.
Variants -> https://rocketcom.atlassian.net/browse/ASTRO-2978
Hover state -> https://rocketcom.atlassian.net/browse/ASTRO-2977
Dev -> Design audit
=> Astro 2977 switch audit

.changeset/many-phones-explain.md, packages/web-components/src/components/rux-clock/rux-clock.scss, packages/web-components/src/global/tokens/_colors-dark.scss
Updates the clock labels to match Figma. 
- removed the border around label
- created new css custom prop `    --clock-label-background-color: var(--color-gsb-global-status-bar);`
- added `padding: 0.094rem 0.625rem; //1.5px 10px ` to label
https://rocketcom.atlassian.net/browse/ASTRO-3153
Noticed by a dev team in #astro channel 
Regressions all fail (obv) so I will update them once this is merged.
Update to match figma
=> Astro 3153 clock labels color

.changeset/olive-flies-march.md, packages/web-components/src/components/rux-tabs/rux-tab/rux-tab.scss, packages/web-components/src/components/rux-tabs/rux-tabs.scss, packages/web-components/src/stories/tab.stories.mdx
Changes:
- adds 1rem left/right padding for large and small rux-tab, as per figma
- adds 30px top/bottom padding for large, 20px for small
- changes text hover color from white to `var(--color-hover)` when tab is not selected
- Nests rux-tab story inside of rux-tabs 
Will have a backstop PR open to update references.
Hover color -> https://rocketcom.atlassian.net/browse/ASTRO-2979
padding -> https://rocketcom.atlassian.net/browse/ASTRO-2980
tab nested in tabs -> https://rocketcom.atlassian.net/browse/ASTRO-2981
On [figma](https://www.figma.com/file/ZtHeSWpISd8hJjN46uY9pm/Astro-UXDS-6.0---Dark-Theme?node-id=2189%3A9014), it states that all tab sizes have a default left/right padding of 16px, but when you inspect it it looks like it's only 10. I've done 16, but wanted to make that known.
As …
=> style(tabs): Astro 2980 tabs aduit

.changeset/tall-pears-lay.md, packages/web-components/src/components.d.ts, packages/web-components/src/components/rux-input/rux-input.scss, packages/web-components/src/components/rux-input/rux-input.tsx, packages/web-components/src/components/rux-input/test/__snapshots__/rux-input.spec.tsx.snap, packages/web-components/src/index.html, packages/web-components/src/stories/input.stories.mdx
Additions:
- Two new named slots, prefix/suffix used to render html on the left and right of input. Open to name change.
- Refactored how show/hide of PW input types visibility icon worked - now using a rux-button with a slotted icon.
- Refactored some markup in order to accomplish styling 
- Added a new event, `ruxfocus` that emits on blur. Just kidding, focus. Added this as I've seen it's a common event, and this allowed me to style the entirety of `rux-input` while it's focused.
- Adds a `With Icons` story to rux-input's stories. This includes a blurb about using the named slots to render the icons
- Updated rux-icon snapshots. 
- Updates padding for each input size, adds a min height for each as well.
Will have a backstop PR open with the reference updates and will merge it once this …
=> Astro 2996 input icons

.changeset/shiny-yaks-hide.md, packages/web-components/src/components/rux-notification/rux-notification.tsx
Notification would not close on default story when entering a value in the closeAfter prop in Storybook
[ASTRO-3101](https://rocketcom.atlassian.net/browse/ASTRO-3101)
=> fix(notification): watch closeAfter to close when updated

.changeset/six-carpets-rush.md, packages/web-components/src/components/rux-slider/rux-slider.tsx
Changes the value equation from`parseInt` to `parseFloat` to allow float values.
https://rocketcom.atlassian.net/browse/ASTRO-3171
Brought up by ACME and Outside Analytics 
Allows for value to be a float, now styling remains correct when using float values.
The default value should be a factor of the step still, otherwise the styling is broken when it first renders. For example, 
```
<rux-slider step=1.5></rux-slider>
```
will default to value = 50, which will screw up the styling.
=> fix(slider): changed value to parseFloat

.changeset/kind-rabbits-press.md, packages/web-components/src/components/rux-button/rux-button.scss
Adds `width: auto` to the host styling of rux-button, allowing the width to be changed without the shadow part.
https://rocketcom.atlassian.net/browse/ASTRO-3218
Astro Monday's
=> style(button): width can now be stlyed without shadow part

packages/web-components/src/components/rux-tag/rux-tag.scss
Replaces px with rem values in css cuz someone forgot to do it the first time even though he told himself he definitely wouldn't forget 
updates radius to use radius token
https://rocketcom.atlassian.net/browse/ASTRO-3250
to out me as forgetful 
jk, consistency
=> style(tag): updated to use rems

packages/starter-kits/angular-starter/angular.json, packages/starter-kits/angular-starter/src/styles.scss
angular starter kit wasn't showing styles 
if you put the css import in styles.scss, it worked locally but not in codesandbox
if you put it in the main.ts, it worked in codesandbox but not locally. 
so I just moved it to angular.json.
I'm still keeping the docs the way they are because I still believe that its the easiest way for running locally
ASTRO-3215
=> fix(angular-starter): move style import to angular.json

.changeset/four-shirts-relax.md, packages/web-components/src/components/rux-table/rux-table-header-cell/rux-table-header-cell.scss, packages/web-components/src/components/rux-table/rux-table-row/rux-table-row.scss, packages/web-components/src/stories/table.stories.mdx
Changes the selected cell color to match figma and updates the table w/ selected row story to have the correct amount of columns. 
Also changes the color on rux-table-header-cell to be `var(--color-text-primary)` so that is is correct in light theme.
https://rocketcom.atlassian.net/browse/ASTRO-2986
Dev -> design audit
=> Astro 2986 table selected

packages/astro-uxds/_content/downloads.md
Links were missing from the Downloads -> Astro Icons hrefs. 
https://rocketcom.atlassian.net/browse/ASTRO-3300
Links were talked over with Amalya
Links work as expected.
=> fix(astro-uxds): added Astro Icons links

.changeset/happy-foxes-bathe.md, packages/angular/src/directives/proxies.ts, packages/web-components/package-lock.json, packages/web-components/package.json, packages/web-components/src/components.d.ts, packages/web-components/src/components/rux-timeline/helpers.ts, packages/web-components/src/components/rux-timeline/readme.md, packages/web-components/src/components/rux-timeline/rux-ruler/rux-ruler.tsx, packages/web-components/src/components/rux-timeline/rux-ruler/test/__snapshots__/rux-ruler.spec.tsx.snap, packages/web-components/src/components/rux-timeline/rux-time-region/rux-time-region.tsx, packages/web-components/src/components/rux-timeline/rux-time-region/test/__snapshots__/rux-time-region.spec.tsx.snap, packages/web-components/src/components/rux-timeline/rux-time-region/test/rux-time-region.spec.tsx, packages/web-components/src/components/rux-timeline/rux-timeline.tsx, packages/web-components/src/components/rux-timeline/rux-track/rux-track.tsx, packages/web-components/src/components/rux-timeline/rux-track/test/__snapshots__/rux-track.spec.tsx.snap, packages/web-components/src/stories/timeline.stories.mdx
* Adds timezone prop to timeline
* VRT fails because the timezone now defaults to UTC. 
ASTRO-3326
The timeline ruler was displaying in the user's local timezone
Does the documentation make sense?
=> feat(timeline): add support for timezones

.changeset/loud-humans-study.md, packages/web-components/src/components/rux-slider/rux-slider.tsx, packages/web-components/src/components/rux-slider/test/__snapshots__/rux-slider.spec.tsx.snap
hides the slider label if none is present
ASTRO-3342
If you have a slider without a label, the label still renders and adds unnecessary padding
Also removed the internal span inside label. I didnt see it being used for anything?
=> fix(slider): dont render label if not present

.changeset/eight-moons-allow.md, packages/web-components/src/components.d.ts, packages/web-components/src/components/rux-table/rux-table.scss
tables in design don't have left/right borders. if you place them inside a container that does a border, its awkward. 
ASTRO-3345
=> fix(table): remove left/right borders

packages/astro-uxds/_content/components/segmented-button.md
Quick fix to remove the mention of form elements in the Help Text sentence on the Segmented Buttons page.
No Jira link
Segmented buttons are not form elements.
=> docs(segmented-button): remove form element mention

.changeset/orange-onions-serve.md, packages/angular/package-lock.json, packages/astro-uxds/package-lock.json, packages/react/package-lock.json, packages/web-components/src/components/rux-checkbox/rux-checkbox.scss, packages/web-components/src/components/rux-checkbox/rux-checkbox.tsx, packages/web-components/src/components/rux-checkbox/test/__snapshots__/rux-checkbox.spec.tsx.snap, packages/web-components/src/components/rux-input/rux-input.scss, packages/web-components/src/components/rux-input/rux-input.tsx, packages/web-components/src/components/rux-input/test/__snapshots__/rux-input.spec.tsx.snap, packages/web-components/src/components/rux-radio/rux-radio.scss, packages/web-components/src/components/rux-radio/rux-radio.tsx, packages/web-components/src/components/rux-radio/test/__snapshots__/rux-radio.spec.tsx.snap, packages/web-components/src/components/rux-slider/rux-slider.tsx, packages/web-components/src/components/rux-slider/test/__snapshots__/rux-slider.spec.tsx.snap, packages/web-components/src/components/rux-textarea/rux-textarea.tsx, packages/web-components/src/components/rux-textarea/test/__snapshots__/rux-textarea.spec.tsx.snap, packages/web-components/src/index.html, packages/web-components/src/stories/radio.stories.mdx
Removes extra margin on form elements when a label is not included. Also removes extra dom nodes (label, slot) on slider, input and textarea using conditional rendering. For other form elements, the element either didn't render extra margin already or it has specific styling on label (checkbox, radio) that inhibited the exclusion of the `<label>` element.
https://rocketcom.atlassian.net/browse/ASTRO-3389
https://github.com/RocketCommunicationsInc/astro/issues/372
Checkbox and Radio both style the `<label>` in order to display anything, so I couldn't omit those when label or slot isn't being used. Instead, I added a conditional class that will override the margin if a label prop or slot isn't being used. 
In all other components, a ternary is being used to conditionally render the …
=> Astro 3389 input top space

packages/web-components/src/stories/input.stories.mdx
The issue with this label not center aligned by default is the margin bottom that is being placed on <label>. It's easy enough to throw a margin-bottom: 0 in the part that's making it horizontal in the first place, so I think that's the answer here. Any strong feelings otherwise?
https://rocketcom.atlassian.net/browse/ASTRO-3333
Horizontal label on input SB was not actually centered.
=> docs(input): added margin-bottom 0 to horizontal label story

.changeset/strange-crabs-taste.md, packages/web-components/src/components/rux-modal/rux-modal.scss, packages/web-components/src/components/rux-modal/rux-modal.tsx
Removes the fixed height form the dialog element in order to allow messages of any length.
https://rocketcom.atlassian.net/browse/ASTRO-3294
Was brought up thru email by Outside Analytics 
I also thought about putting a shadow part on the dialog. Thoughts? 
Allows for longer modal message's
=> fix(modal): removed fixed height on dialog

packages/web-components/src/stories/modal.stories.mdx
This fixes the imports for the components, and also adds `rux-button-group`, which is necessary to display the buttons with appropriate padding between them.
=> docs: Add rux-button-group to cherry picking

.changeset/wet-buckets-smoke.md, packages/web-components/src/components/rux-push-button/rux-push-button.scss
fixes https://github.com/RocketCommunicationsInc/astro/issues/382 
applies the color styles figma is using
updates the bg-colors to their appropriate context specific token
ASTRO-3419
noticed the padding is way off here too but we'll need to tackle that during spacing
=> fix(push-button): hover styles

.changeset/brown-panthers-study.md, packages/web-components/src/components/rux-tabs/rux-tab/rux-tab.scss, packages/web-components/src/components/rux-tabs/rux-tab/rux-tab.tsx, packages/web-components/src/components/rux-tabs/test/rux-tabs.e2e.js
Tab were being styled entirely on the host + attributes and basically weren't shadow domed at all. Which caused issues when you pull in something like Tailwind
ASTRO-3494
https://github.com/RocketCommunicationsInc/astro/issues/391
=> fix(tab): prevent light dom styles

packages/react/package-lock.json, packages/web-components/src/stories/button.stories.mdx, packages/web-components/src/stories/clock.stories.mdx, packages/web-components/src/stories/select.stories.mdx, packages/web-components/src/stories/time-region.stories.mdx
Fixes the unpkg url in the cherry picking section of the docs for those who were using the wrong one:
- rux-button
- rux-select
- rux-time-region
https://rocketcom.atlassian.net/browse/ASTRO-3446
Since there were only 3 sections to update, I didn't make a reusable cherry picking component or update the auto-gen to handle this. Let me know if I should - it just felt like a lot of work for a quick fix. 
Correct urls for cherry picking in our docs
=> docs: fixed cherry picking section unpkg url button, select, time-region

.changeset/blue-taxis-wash.md, packages/react/package-lock.json, packages/web-components/package.json, packages/web-components/src/components.d.ts, packages/web-components/src/components/rux-modal/rux-modal.tsx, packages/web-components/src/components/rux-modal/test/rux-modal.e2e.js
Fixes a bug introduced in the modal backport that removed the true/false in the ruxmodalclosed detail when using the default comfirm/deny buttons.
Adds tests to prevent this from happening again.
I've also added a `test.unit.silent` command to the web-components package that github actions will use when testing in order to avoid all of the console noise - if react tests fail we'll actually see the failures now. 
https://rocketcom.atlassian.net/browse/ASTRO-3596
https://github.com/RocketCommunicationsInc/astro/issues/421
Allows for users to determine if the confirm or deny button was pressed when using the default modal footer.
=> fix(modal): default buttons emit true or false in event detail

.changeset/soft-dolls-jump.md, packages/web-components/src/components/rux-pop-up-menu/rux-pop-up-menu.tsx, packages/web-components/src/index.html
When there is a horizontal scroll bar present and a pop-up anchor is used beyond the window.innerWidth, the pop-up would render in the wrong spot. This adds support for this case by computing the window.scrollX value in the setMenuPosition function. 
https://rocketcom.atlassian.net/browse/ASTRO-3597
https://github.com/RocketCommunicationsInc/astro/issues/422
This change gets the `window.scrollX` value, stores it, and adds it to the `left` calculation if the pop-up anchor is placed at a larger `left` value than `window.innerWidth`
Pop up menu rendering incorrectly if anchor was beyond a horizontal scrollbar.
=> fix(pop-up): setMenuPosition now accounts for scrollX

.changeset/neat-cameras-grab.md, packages/web-components/src/components.d.ts, packages/web-components/src/components/rux-input/rux-input.scss, packages/web-components/src/components/rux-input/rux-input.tsx, packages/web-components/src/components/rux-input/test/index.html, packages/web-components/src/components/rux-input/test/rux-input.e2e.js, packages/web-components/src/index.html, packages/web-components/src/stories/input.stories.mdx
Adds official support for input type=time. Styles the icon in chrome as well.
https://rocketcom.atlassian.net/browse/ASTRO-3672
https://github.com/RocketCommunicationsInc/astro/issues/435
Adds tests and updates sb.
https://github.com/RocketCommunicationsInc/astro/issues/435
=> Astro 3672 time input

packages/web-components/package-lock.json, packages/web-components/package.json
This change updates the `@astrouxds/design-tokens` library from `2.0.0-beta.6` to `2.0.0-beta.7`. This is necessary to use the `--spacing-*` tokens.
=> Update Design Tokens

.changeset/slow-apples-build.md, packages/web-components/src/components/rux-modal/rux-modal.tsx
Modal was emitting 2 `ruxmodalclosed` events when the modal was closed by an off click.
https://rocketcom.atlassian.net/jira/software/c/projects/ASTRO/boards/32?modal=detail&selectedIssue=ASTRO-3912&assignee=6098f2aa8cbda70068049d4c
Don't want double events being emitted
=> Astro 3912 modal extra event

packages/web-components/package-lock.json, packages/web-components/package.json, packages/web-components/src/components/rux-button-group/test/__snapshots__/rux-button-group.spec.tsx.snap, packages/web-components/src/components/rux-button/rux-button.scss, packages/web-components/src/components/rux-button/test/__snapshots__/rux-button.spec.tsx.snap, packages/web-components/src/components/rux-checkbox/rux-checkbox.scss, packages/web-components/src/components/rux-input/rux-input.scss, packages/web-components/src/components/rux-push-button/rux-push-button.scss, packages/web-components/src/components/rux-radio/rux-radio.scss, packages/web-components/src/components/rux-segmented-button/rux-segmented-button.scss, packages/web-components/src/components/rux-select/rux-select.scss, packages/web-components/src/components/rux-slider/rux-slider.scss, packages/web-components/src/components/rux-switch/rux-switch.scss, packages/web-components/src/components/rux-tabs/rux-tab/rux-tab.scss, packages/web-components/src/components/rux-textarea/rux-textarea.scss, packages/web-components/src/global/_variables.scss
House keeping
* upgrades to tokens@beta.8
* replaces temp '--disabled-opacitycustom prop with the--opacity-disabled` token.
* updates the useless failing jest snapshots for button
* Prettier keeps adding spaces to the / in `--button-type-shorthand: var(--button-type-size)/var(--button-type-line-spacing) var(--type-family);` so I threw in a prettier-ignore for now because I couldn't figure out what that rule was.
=> refactor(web-components): use opacity-disabled token

.changeset/heavy-ducks-pump.md, packages/angular-workspace/projects/angular/src/directives/proxies-list.ts, packages/starter-kits/svelte-starter/README.md, packages/starter-kits/vue-starter/src/main.js, packages/web-components/package-lock.json, packages/web-components/package.json, packages/web-components/src/stories/astro-sandboxes/forms/vue/validation/src/main.js, packages/web-components/stencil.config.ts
removes the dist-custom-elements-bundle. Restores like 5 seconds to our build process
[Stencil is deprecating the dist custom elements bundle](https://stenciljs.com/docs/custom-elements-bundle). dist-custom-elements is way superior for treeshaking anyway. 
This has to be a breaking change because our own docs were still referencing the old custom-elements build for Vue and Svelte so there's a chance someone out there is still using it in their project.
=> feat(): remove custom-elements-bundle

.changeset/polite-spoons-attack.md, .github/workflows/pull-request.yml, packages/angular/src/directives/angular-component-lib/utils.ts, packages/angular/src/directives/proxies-list.ts, packages/angular/src/directives/proxies.ts, packages/react/src/components.tsx, packages/web-components/.storybook/preview-head.html, packages/web-components/cypress/support/index.js, packages/web-components/src/components.d.ts, packages/web-components/src/components/rux-button-group/readme.md, packages/web-components/src/components/rux-button/readme.md, packages/web-components/src/components/rux-dialog/readme.md, packages/web-components/src/components/rux-dialog/rux-dialog.scss, packages/web-components/src/components/rux-dialog/rux-dialog.tsx, packages/web-components/src/components/rux-dialog/test/__snapshots__/rux-dialog.spec.tsx.snap, packages/web-components/src/components/rux-dialog/test/index.html, packages/web-components/src/components/rux-dialog/test/rux-dialog.e2e.js, packages/web-components/src/components/rux-dialog/test/rux-dialog.spec.tsx, packages/web-components/src/stories/dialog.stories.mdx, packages/web-components/src/stories/modal.stories.mdx, packages/web-components/src/stories/timeline.stories.mdx
creates a dialog component and deprecates modal
ASTRO-3893
Dev started calling this component Modal awhile ago, but it's called 'Dialog' in design. It's time to rip the bandaid off. 
Although it is slightly weird we will ship both for now
=> feat(dialog): create dialog component

packages/astro-uxds/_content/components/card.md
on astrouxds the card page sb preview cuts off
=> fix(astro-uxds): increase card height in story preview

.changeset/silver-emus-arrive.md, .github/workflows/pull-request.yml, packages/angular/src/directives/proxies.ts, packages/web-components/package-lock.json, packages/web-components/src/components.d.ts, packages/web-components/src/components/rux-tree-node/readme.md, packages/web-components/src/components/rux-tree-node/rux-tree-node.tsx, packages/web-components/src/components/rux-tree/test/index.html, packages/web-components/src/components/rux-tree/test/rux-tree.e2e.js, packages/web-components/src/stories/tree.stories.mdx
Adds `ruxtreenodeexpanded` and `ruxtreenodecollapsed` events to rux-tree-node. This event emits the node ID, similar to how the existing expanded event works. 
Tests were added to cover all events, including selected. 
https://rocketcom.atlassian.net/browse/ASTRO-4081
https://github.com/RocketCommunicationsInc/astro/issues/571
Issue raised by user. Allows for easier saving of state when using rux-tree.
=> Astro 4081 tree event

.github/workflows/pull-request.yml, packages/web-components/src/components.d.ts, packages/web-components/src/components/rux-dialog/readme.md, packages/web-components/src/components/rux-dialog/rux-dialog.tsx, packages/web-components/src/components/rux-modal/readme.md, packages/web-components/src/components/rux-modal/rux-modal.tsx
Adds a better description on how the ruxmodalclosed event works for modal/dialog. 
https://rocketcom.atlassian.net/browse/ASTRO-4078
I only updated the event decorator (and by extension the readmes). I could also add something to the SB if we think it's needed.
The ruxmodalclosed event was ambiguous in that it returns either boolean or null.
=> docs(modal, dialog): updated ruxmodalclosed event description

packages/astro-uxds/_content/_data/navigation.json, packages/astro-uxds/_content/design-guidelines/glossary.md, packages/astro-uxds/_content/patterns/sign-in.md, packages/astro-uxds/netlify.toml
Updates the glossary page of astrouxds with new copy/terms. Moves the sign-in pattern to be in /patterns instead of /components.
With that sign in move, I'm thinking we can get rid of the SB iframe and convert it to the 'internal.template.njk' that the other patterns are using. Thoughts? 
https://rocketcom.atlassian.net/browse/ASTRO-3999
Glossary update
=> Astro 3999 glossary update

.changeset/loud-planes-accept.md, .changeset/pink-mangos-switch.md, .changeset/violet-buttons-arrive.md, packages/web-components/src/components.d.ts, packages/web-components/src/components/rux-tabs/rux-tab/rux-tab.scss, packages/web-components/src/components/rux-tabs/rux-tab/rux-tab.tsx, packages/web-components/src/components/rux-tabs/rux-tabs.scss
Part of https://github.com/RocketCommunicationsInc/astro/pull/589. Breaking into it's own PR because its pretty chonky and required some API changes. 
Tabs relied entirely on host styles so I needed to create an internal class and an explicit `small` prop/attr. 
There is one major breaking change in that rux-tab by itself is now large by default. It was previously small for some reason, which didn't make sense because rux-tabs is large by default. 
Our dev implementation of design is actually way off after looking at Figma closer. This should hopefully get smoothed out in the spacing effort, I was only concerned with getting our VRT to pass here.
=> fix(rux-tabs): can no longer change shadow dom typography styles

packages/starter-kits/react-starter/init.js, packages/starter-kits/react-starter/package.json
The npx command for react-starter was busted. 
This changes it to be async in order to avoid the script writing files before directory changes.
I published a dummy command and tested it out as well as installing afterward. 
This also bumps the astro/react version in starter-kits to be the latest (6.11)
https://rocketcom.atlassian.net/browse/ASTRO-4098
https://github.com/RocketCommunicationsInc/astro/issues/588
=> React npx fix

.changeset/forty-adults-rest.md, packages/web-components/src/components.d.ts, packages/web-components/src/components/rux-dialog/rux-dialog.scss
Adds scrollbars to dialog.
Additions to the rux-diallog__content class:
- white-space: no-wrap
- Overflow: auto 
- max-height: 100%
- Added a box shadow to the scrollbar corner.
This allows for scrollbars to appear and be styled correctly. We also checked the message shadow part to ensure that these could be overridden by devs. 
https://rocketcom.atlassian.net/browse/ASTRO-1971
Updates dialog to match design (scrollbars).
Firefox sucks so there is a bit of a visual difference - no box shadow really.
In figma, the design has the horizontal scrollbar spanning the entire width (even under the vertical). I'm not sure that's something we can do - let me know if you have any ideas. Below is the Figma design for reference.
https://www.figma.com/file/3tYLyBkvKYOdUysPk6Fu60/Astro-UXDS-7.0-BETA---Da …
=> Astro 1971 dialog scrollbars

.github/workflows/pull-request.yml
Adds a `wait-on-timeout` option and sets it to 90 sec in order to ensure that the stencil start command has finished before the cypress tests start.
Since it's a `wait-on`, it will keep pinging the local server until it responds and is ready to test, so it won't take 90 sec to start tests, that's just how long it _can_ wait to start tests. 
https://rocketcom.atlassian.net/browse/ASTRO-4094
Should fix the issue of the Cypress e2e tests running before the stencil start command has finished.
=> test(ga): added wait on timeout

packages/starter-kits/angular-starter/src/app/app.component.html
Removed the spinner from the angular start-up page
https://rocketcom.atlassian.net/browse/ASTRO-3962
The spinner was confusing people, so we removed it.
=> docs(starter kits): removed the spinner from angular starter page

.changeset/eight-flowers-exist.md, packages/web-components/src/global/_reset.scss
Maria and I merged in a change to links on hover which was supposed to be into next, not main. Reverting here and will take the change and add it to the next branch.
=> revert(wc): reverted link change that was supposed to be in next

packages/web-components/src/stories/tabs.stories.mdx
Just fixes some typos I noticed in the documentation.
=> Fix typos in cherry picking for tabs

.changeset/few-candles-pull.md, packages/web-components/src/components.d.ts, packages/web-components/src/components/rux-slider/readme.md, packages/web-components/src/components/rux-slider/rux-slider.tsx, packages/web-components/src/components/rux-slider/test/index.html, packages/web-components/src/components/rux-slider/test/rux-slider.e2e.js, packages/web-components/src/stories/slider.stories.mdx
Added a ruxChange event to rux-slider. 
Adds tests for events on slider.
https://rocketcom.atlassian.net/browse/ASTRO-4214
https://github.com/RocketCommunicationsInc/astro/issues/609
Adds the missing onchange event to slider.
=> Feat(slider): added onChange event

.github/workflows/pull-request.yml
Upped the timeout from 90 to 110 for cypress. I hate it 
This will stop tests from failing on rux-button-group.
=> test(ga): bumped timeout for cypress :)

.changeset/good-ears-flow.md, packages/web-components/src/components/rux-icon/rux-icon.tsx, packages/web-components/src/components/rux-icon/test/__snapshots__/rux-icon.spec.tsx.snap, packages/web-components/src/components/rux-notification/rux-notification.tsx, packages/web-components/src/components/rux-notification/test/__snapshots__/rux-notification.spec.tsx.snap
This is a clone of https://github.com/RocketCommunicationsInc/astro/pull/627.
https://rocketcom.atlassian.net/browse/ASTRO-4317
https://github.com/RocketCommunicationsInc/astro/issues/625
Removes the title attr from rux-icon. The title attr is warned against use by web standards.
=> Icon title

packages/web-components/src/stories/astro-uxds/welcome/javascript.stories.mdx
The code formatting in the Methods section was improper.  Reformatted so it is consistent with the rest of the page.
The code formatting looked odd.  Now it is more consistent with the rest of the page.
=> Fix code formatting in Methods section

packages/astro-uxds/_content/getting-started/_readme.md
Change the browser chart to use checkmarks (&check;) instead of X's to indicate a supported browser.
The 'X' marks in the supported browser chart might indicate that the browsers were not supported.  A checkmark seems like a more obvious way to indicate support.
=> Update README browser chart with checkmarks

packages/web-components/src/stories/astro-uxds/welcome/react.stories.mdx
Correct misspelled word 'trigerring' to be correctly spelled as 'triggering'.
=> Fix spelling error

.changeset/sweet-chefs-end.md, packages/web-components/src/components/rux-timeline/rux-time-region/rux-time-region.tsx, packages/web-components/src/components/rux-timeline/rux-track/rux-track.tsx
Steps to reproduce:
Change a Time Region's start or end attribute after it's already been rendered. It should update accordingly.
ASTRO-4314
The time region position is calculated from it's parent Track. The problem is that Track doesn't know when a Time Region's start or end date changes. 
Went with an event,  but maybe a mutation observer would've been the better choice? 
Also, tried to write a test for this and gave up.
```
it('updates the position of an event when its start or end date is changed', () => {
cy.get('rux-time-region')
.invoke('prop', 'start', '2022-08-08T01:00')
.should('have.css', 'grid-area', '1 / 62 / auto / 2882')
})
```
Passes without any code changes. 
Same test in Playwright:
```
test('homepage has Playwright in title and get started link linking to the intro …
```
=> fix(timeline): editing time events

.github/workflows/pull-request.yml
This was implemented in main, but not next. This will allow our tests to pass first try without rux-button-group failing.
=> chore: extend cypress tiemout

.changeset/lazy-pumas-trade.md, .github/workflows/pull-request.yml, package.json, packages/web-components/package-lock.json, packages/web-components/package.json, packages/web-components/src/global/global.scss
Publishes our new typography utility classes from our design tokens to the global css so peeps can use it.
* .rux-body-1
* .rux-body-1-bold
* .rux-body-2
* .rux-body-2-bold
* .rux-body-3
* .rux-body-3-bold
* .rux-control-body-1
* .rux-control-body-1-bold
* .rux-heading-1
* .rux-heading-1-bold
* .rux-heading-2
* .rux-heading-3
* .rux-heading-4
* .rux-heading-5
* .rux-heading-6
* .rux-display-1
* .rux-display-2
* .rux-monospace-1
ASTRO-4339
Using raw design tokens for typography sucks
* Additional tickets will be created to clean up the import process a bit (ie not importing from /dist)
* These are imported by default without any way to opt out and will add to the bundle size. Because theres so few, it should be negligible, but providing a way to opt in/out is a high priority for me. …
=> Typography Utility Classes

.changeset/large-garlics-hear.md, .changeset/lovely-spies-serve.md, .changeset/strong-dogs-crash.md, .changeset/weak-mice-behave.md, package-lock.json, packages/astro-uxds/package-lock.json, packages/web-components/src/components.d.ts, packages/web-components/src/components/rux-classification-marking/rux-classification-marking.scss, packages/web-components/src/components/rux-classification-marking/test/index.html
Changed min-height attribute on .rux-classification--banner to reflect spacing design token to match height in Figma.
[https://rocketcom.atlassian.net/browse/ASTRO-3846]
This change makes the heights of the rux-classification-marking component match those in Figma.
- [ x] Bug fix
- [ x] Regressions are passing and/or failures are documented
=> fix: spacing for classification-markings.

.changeset/gorgeous-rice-repeat.md, packages/astro-uxds/package-lock.json, packages/web-components/src/components.d.ts, packages/web-components/src/components/rux-switch/rux-switch.scss, packages/web-components/src/components/rux-switch/test/index.html
Add design tokens to rux-switch to bring in line with Figma design
**Question**: This is one of the components that requires actual height and width declarations. For those I used the --spacing tokens and some calculation but I'm wondering if that's the best path. Is there a better choice?
**Comment**: If you're wondering why components.d.ts was touched.. My stencil compiler keeps changing it when compiling. I had to bring it back inline with next.
[ASTRO-3866](https://rocketcom.atlassian.net/browse/ASTRO-3866)
I added inset shadows rather than borders to the thumb switch and rail in order to allow easier sizing via tokens.
Part of the astro spacing adjustment initiative!
=> Km 3866 switch toggle spacing

.changeset/dull-cobras-wash.md, .changeset/famous-eels-dress.md, packages/web-components/src/components.d.ts, packages/web-components/src/components/rux-checkbox/rux-checkbox.scss, packages/web-components/src/components/rux-checkbox/test/index.html
Style changes to make checkbox match Figma. Changes include updated margin, adding in border-radius for the box itself and updating the checkmark itself.
[3845](https://rocketcom.atlassian.net/browse/ASTRO-3845)
Makes the checkbox component better match that in Figma. Adds in ftl belt and holster component for testing.
- [ x] Bug fix
- [ x] Regressions are passing and/or failures are documented
=> Fm 3845 checkbox spacing

.changeset/rude-buckets-fail.md, .github/workflows/pull-request.yml, packages/web-components/src/components/rux-global-status-bar/rux-global-status-bar.scss, packages/web-components/src/components/rux-global-status-bar/rux-global-status-bar.tsx, packages/web-components/src/components/rux-global-status-bar/test/__snapshots__/rux-global-status-bar.spec.tsx.snap, packages/web-components/src/components/rux-global-status-bar/test/index.html, packages/web-components/src/components/rux-monitoring-icon/rux-monitoring-icon.scss, packages/web-components/src/components/rux-monitoring-icon/test/index.html
Spacing updates for GSB and it's close counterparts, monitoring icon and app-state.
GSB -> https://rocketcom.atlassian.net/browse/ASTRO-3849
App state -> https://rocketcom.atlassian.net/browse/ASTRO-3843
Monitoring icon -> https://rocketcom.atlassian.net/browse/ASTRO-3850
I tackled monitoring icon with GSB since it's a very common use case, and needed it for Figma VRT's anyway.
App state is a separate component in Figma, but it part of GSB in code - hence why it's here too. 
Spacing effort 👾 
Monitoring icon is a bit off still due to the status symbol mismatches in size - this will be addressed at a later stage when we swap in SVG's for the status symbols. 
The only thing not lining up in GSB is the text due to a font difference. It's like half a px off. 
Clock does not look the same …
=> Mj 3849 gsb spacing

packages/astro-uxds/_content/getting-started/designers.md
Added Figma 6.0 wireframe theme link
No ticket. Just a quick fix for a request from a KM user.
Adds in the missing link to the Wireframe 6.0 file.
=> Added Figma 6.0 wireframe theme link

packages/astro-uxds/_content/downloads.md
Changed the Figma link to our profile page with all of our files instead of just the dark 6.0 theme file.
None. Quick fix for a KM user.
Link is incorrect for showing all Figma work.
=> Updated downloads page with correct Figma link

.changeset/thin-flowers-carry.md, packages/angular/package-lock.json, packages/astro-uxds/package-lock.json, packages/react/package-lock.json, packages/web-components/package-lock.json, packages/web-components/src/components/rux-progress/rux-progress.scss, packages/web-components/src/components/rux-progress/test/index.html
Current rux-progress in Firefox was out of alignment with the size and visuals of rux-progress in other browsers. Adding a box-sizing: border-box property to run-progress fixed this issue while not changing the design or size in other evergreen browsers.
[ASTRO-4363](https://rocketcom.atlassian.net/browse/ASTRO-4363)
Noticed a visual defect in the current branch while working on the spacing initiative for next branch.
=> add border-box sizing to fix visual glitch

.changeset/thirty-carrots-report.md, packages/astro-uxds/package-lock.json, packages/web-components/src/components/rux-radio-group/rux-radio-group.scss, packages/web-components/src/components/rux-radio-group/test/index.html, packages/web-components/src/components/rux-radio/rux-radio.scss, packages/web-components/src/components/rux-radio/test/index.html
Changes made to rux-radio and rux-radio-group to bring them in line with astro design tokens.
[ASTRO-3859](https://rocketcom.atlassian.net/browse/ASTRO-3859)
I've noticed that I'm:
1) combining --spacing-4 and --spacing-1 to make 20px a lot.. and
2) using spacing to define the height and width of a thing (such as the radio button inner and outer circle).
I'm starting to wonder if we should have a token/set of tokens specifically relating to width/height which would be separate from what we use for padding and margin.. or if width and height should be assigned without the use of tokens.
Part of the Astro spacing initiative!
=> Km 3859 radio button spacing

.changeset/shiny-cameras-remember.md, packages/web-components/src/components/rux-slider/rux-slider.scss, packages/web-components/src/components/rux-slider/test/index.html
Added design tokens to rux-slider and adjusted it to match Astro design specifications.
[ASTRO-3864](https://rocketcom.atlassian.net/browse/ASTRO-3864)
Part of the Astro spacing initiative!
The thinner part of the track is about 1px off from Figma. It doesn't affect overall sizing.
The design specification shows the range thumb (the indicator) aligning itself with the middle point of the indicator centered over the end of the track. <input type="range"> only allows the indicator to align its left edge with the left end of the track and the right edge with the right edge of the track. After a lot of testing, I ultimately refactored the background to give the illusion of being slightly less than the whole track, and added a new background shape to round the 'left-edge' of the track.
=> Km 3864 slider spacing

.changeset/old-bottles-poke.md, packages/web-components/src/components/rux-textarea/rux-textarea.scss, packages/web-components/src/components/rux-textarea/rux-textarea.tsx, packages/web-components/src/components/rux-textarea/test/__snapshots__/rux-textarea.spec.tsx.snap, packages/web-components/src/components/rux-textarea/test/index.html
Add spacing tokens and align to Astro design specifications. Additionally, in service to fixing an issue caused by padding in Firefox, I added a wrapper around textarea and added padding to that. Explained more thoroughly below.
[ASTRO-3842](https://rocketcom.atlassian.net/browse/ASTRO-3842)
Part of the Astro spacing initiative!
Adding spacing to text areas adds a range of issues that you wouldn't expect, but it boils down to two issues:
**Issue 1: Padding**
Adding too much padding to a textarea breaks resizing in safari. The user becomes unable to get to the resizing handle for whatever reason.
After an extensive amount of testing, troubleshooting, and research I styled a new resizable wrapper around textarea. Safari doesn't have trouble with resize and padding when it is not attached to …
=> Km 3842 rux textarea spacing alignment

.changeset/spotty-tips-jam.md, packages/web-components/src/components.d.ts, packages/web-components/src/components/rux-checkbox-group/rux-checkbox-group.scss, packages/web-components/src/components/rux-checkbox-group/test/index.html, packages/web-components/src/components/rux-checkbox/rux-checkbox.scss, packages/web-components/src/components/rux-checkbox/test/index.html
This commit includes changes to both checkbox and checkbox group. For checkbox, an error was corrected where the hover state of the input box was no longer working due to a border vs box-shadow discrepancy. Margin of zero was also applied to the base checkbox input in order to solve a bug appearing on Safari that was actually a bug on all browsers where the input was obeying the user-agent stylesheet, which did not necessarily have a margin of 0. This fix allowed the arbitrary value of -7px on margin-left that was set on the label to be removed.
For checkbox group, the css was modified so that the group matched design which included adding a width specification for the group and modifying the margin with a design token.
[Checkbox Group …
=> Fm 4361 checkbox group spacing

.changeset/young-apricots-grin.md, packages/web-components/src/components/rux-dialog/rux-dialog.tsx, packages/web-components/src/components/rux-dialog/test/index.html, packages/web-components/src/components/rux-dialog/test/rux-dialog.e2e.js, packages/web-components/src/components/rux-modal/rux-modal.tsx, packages/web-components/src/stories/dialog.stories.mdx
Adds tabindex's to the default (prop version) of the dialog footer. 
Adds the ability to trigger the deny button on an escape key press.
Added a section to dialog's SB page about keyboard interactions.
Added a commented out test - cypress does not allow for a keyboard press if it's not a form element. We will be switching these to playwright soon anyway.
Dialogs tests were still using modals - I changed that to be dialogs.
https://rocketcom.atlassian.net/browse/ASTRO-4456
https://github.com/RocketCommunicationsInc/astro/issues/675
I've thought up a way to provide this keyboard functionality to folks using slots for the footer too, but it will need some more testing and is beyond the scope of this ticket. 
I've also added these changes to rux-modal
GitHub issue - provides better keyboard …
=> feat(dialog): add better keyboard support

.changeset/good-emus-confess.md, packages/web-components/src/components/rux-menu-item/rux-menu-item.scss, packages/web-components/src/components/rux-pop-up-menu/rux-pop-up-menu.scss, packages/web-components/src/components/rux-pop-up-menu/test/index.html
Add design spacing tokens to rux-pop-up-menu and rux-menu-item and align to Astro design specs.
[ASTRO-3856](https://rocketcom.atlassian.net/browse/ASTRO-3856)
Astro spacing initiative!
No issues, but this was difficult to test in the ftl-holster because of all the moving parts involved. Still, I believe that spacing is aligned to design intentions.
=> Km 3856 popup component spacing

.changeset/weak-spoons-compare.md, packages/web-components/src/components/rux-tabs/rux-tab/rux-tab.tsx, packages/web-components/src/components/rux-tabs/test/index.html
Added a shadow part to rux-tab in order to facilitate styling text and border colors
(Redid pull request as I accidentally requested to main the first time, sorry!)
[ASTRO-3657](https://rocketcom.atlassian.net/browse/ASTRO-3657)
Some custom css properties were deprecated, so we want to give developers that customizability back via shadow parts.
=> Km 3657 tabs styling parts

.changeset/sixty-papayas-chew.md, .changeset/tidy-cycles-sleep.md, packages/web-components/src/components/rux-push-button/rux-push-button.scss, packages/web-components/src/components/rux-push-button/rux-push-button.tsx, packages/web-components/src/components/rux-push-button/test/__snapshots__/rux-push-button.spec.tsx.snap, packages/web-components/src/components/rux-push-button/test/index.html
Added parts to rux-push-button to allow styling that was lost when the old css custom styles were deprecated. Changes part 'label' to 'container' for consistency with standard rux-button.
[ASTRO-3656](https://rocketcom.atlassian.net/browse/ASTRO-3656)
I came up with two ways to style rux-push-button when it is checked.
1) Add a part that only appears on <label> when checked='true' so that it can be targeted and styled
2) Use rux-push-button[checked]::part(label) to style the button when checked.
~~I decided to go with #1 since I believe it simplifies things for a developer using the component.~~
~~To that end I ultimately added 4 parts.~~
~~buttonOn, buttonOff, iconOn, iconOff~~
~~These cover the checked and unchecked button states for components that may be included in the button.~~ …
=> Km 3656 push button add parts

.changeset/mean-wasps-fold.md, packages/web-components/src/common/functional-components/FormFieldMessage/FormFieldMessage.tsx, packages/web-components/src/common/functional-components/FormFieldMessage/form-field-message.scss, packages/web-components/src/components/rux-input/rux-input.scss, packages/web-components/src/components/rux-input/test/index.html, packages/web-components/src/components/rux-radio-group/rux-radio-group.scss, packages/web-components/src/components/rux-select/rux-select.scss, packages/web-components/src/components/rux-textarea/rux-textarea.scss
Add spacing tokens to FormFieldMessage and adjust error icon to be up to date with figma icon.
[ASTRO-3831](https://rocketcom.atlassian.net/browse/ASTRO-3831)
I noticed that[ figma](https://www.figma.com/file/3tYLyBkvKYOdUysPk6Fu60/Astro-UXDS-7.0-BETA---Dark-Theme?node-id=261%3A1570) shows the ability for a developer to change the error icon. Right now I don't believe that is possible. Might need to address this.
Part of the astro spacing initiative!
=> add spacing tokens adjust/test

packages/web-components/package-lock.json, packages/web-components/package.json, packages/web-components/src/components/rux-global-status-bar/rux-global-status-bar.scss, packages/web-components/src/global/_variables.scss, packages/web-components/src/global/global.scss, packages/web-components/src/global/tokens/_colors-dark.scss, packages/web-components/src/global/tokens/_colors-global.css, packages/web-components/src/global/tokens/_colors-light.css, packages/web-components/src/global/tokens/_tokens.scss
Updates our web components to use the new design token output structure
* removes the root-variables sass imports and uses [meta.module-variables](https://sass-lang.com/documentation/modules/meta#module-variables) instead. will revisit the approach to use sass here in a separate ticket. 
* removes the individual token files that just imported from node_mods 
* shaves off 2 KB from astro-web-components.css and 2KB from global-status-bar
Our design token package has been updated to have a more intuitive file structure. Tokens are broken down by tier (ref/sys/comp).
Our tokens were previously exporting a custom "internal" directory that we consumed. All that did was change the selector from :root to `@mixin root-variables` so that we could use it as part of the GSB light theme workaround. …
=> refactor(web-components): use new token structure

.changeset/tricky-coins-clap.md, packages/web-components/src/components/rux-button-group/rux-button-group.scss, packages/web-components/src/components/rux-button/rux-button.scss, packages/web-components/src/components/rux-button/rux-button.tsx, packages/web-components/src/components/rux-button/test/index.html
Add spacing tokens to. rux-button and bring in line with Astro design specs, also a tiny change to rux-button-group to add a spacing token there as well.
[Astro-4479](https://rocketcom.atlassian.net/browse/ASTRO-4479)
Part of the Astro design token spacing initiative!
=> implement spacing tokens on rux-button

.changeset/eighty-falcons-notice.md, packages/web-components/src/components/rux-segmented-button/rux-segmented-button.scss, packages/web-components/src/components/rux-segmented-button/test/index.html
Added spacing tokens to rux-segmented-buttons and aligned to Astro design
[ASTRO-4480](https://rocketcom.atlassian.net/browse/ASTRO-4480)
Just a note while I was in there I noticed that there is a comment about defaulting to medium in 7.0 and it does not seem to be implemented yet. I couldn't find a ticket but there might be one.
Part of the astro spacing initiative!
=> Km 4480 segmented button spacing tokens

.changeset/slimy-clocks-taste.md, packages/web-components/src/components/rux-segmented-button/rux-segmented-button.scss, packages/web-components/src/components/rux-segmented-button/rux-segmented-button.tsx
Changed the default side of rux-segmented-button to medium.
[ASTRO-4503](https://rocketcom.atlassian.net/browse/ASTRO-4503)
This change brings rux-segmented-button defaults (medium size) inline with other components in 7.0
I'm not sure if I chose the correct changes here? It IS a breaking change if anyone was not declaring a size and expects the small sizing.. but it didn't seem major. If I should redo the changes let me know.
=> rux-segmented-button change default size

.changeset/thick-humans-applaud.md, packages/web-components/src/components/rux-input/rux-input.tsx, packages/web-components/src/components/rux-input/test/__snapshots__/rux-input.spec.tsx.snap
Rux-input: added an 'input-field' part to the wrapper surrounding <input> so that it can be styled by the developer.
[ASTRO-3655](https://rocketcom.atlassian.net/browse/ASTRO-3655)
I previously made this branch off of next but remade it for main. :)
Adds the ability to style the input more fully since the custom css styles are being deprecated.
=> rux-input add 'input-field' part

.changeset/warm-keys-look.md, packages/web-components/src/components/rux-button/rux-button.scss, packages/web-components/src/components/rux-checkbox/rux-checkbox.scss, packages/web-components/src/components/rux-input/rux-input.scss, packages/web-components/src/components/rux-push-button/rux-push-button.scss, packages/web-components/src/components/rux-radio/rux-radio.scss, packages/web-components/src/components/rux-segmented-button/rux-segmented-button.scss, packages/web-components/src/components/rux-slider/rux-slider.scss, packages/web-components/src/components/rux-switch/rux-switch.scss, packages/web-components/src/components/rux-tabs/rux-tab/rux-tab.scss, packages/web-components/src/components/rux-textarea/rux-textarea.scss, packages/web-components/src/global/_variables.scss
* replaces all instances of local --disabled-opacity custom prop with a proper --opacity-disabled design token
* removes --disabled-opacity 
* removes local --radius-base bc its a token
7.0 prep
=> refactor(web-components): replace disabled-opacity with DT

packages/web-components/src/components/rux-checkbox-group/rux-checkbox-group.scss, packages/web-components/src/components/rux-slider/rux-slider.scss, packages/web-components/src/components/rux-textarea/rux-textarea.scss, packages/web-components/src/global/_variables.scss, packages/web-components/src/stories/checkbox-group.stories.mdx, packages/web-components/src/stories/input.stories.mdx, packages/web-components/src/stories/radio-group.stories.mdx, packages/web-components/src/stories/slider.stories.mdx, packages/web-components/src/stories/textarea.stories.mdx
* removes the internal `--spacing-input-label-top` and `--spacing-input-label-left` vars in favor of DT. 
* fixes an issue where some form labels werent consistent across components 
```
<div style="display: flex;">
<rux-input label="one"></rux-input>
<rux-textarea label="one"></rux-textarea>
</div>
```
=> refactor: remove spacing-label local vars in favor of DT

.changeset/thin-schools-beam.md, packages/web-components/src/components/rux-tabs/rux-tab/rux-tab.tsx, packages/web-components/src/components/rux-tabs/rux-tabs.tsx, packages/web-components/tests/tabs.spec.ts
This adds filtering based on parent element to the `reset()` method on rux-tabs. 
This change allows for multiple rux-tabs to exist on the same page and not hide each others content. 
Here's some code to throw in the `src/index.html` to try it out locally: 
```
<div class="mydiv">
<rux-tabs id="tab-set-id-1">
<rux-tab id="tab-id-1">Top 1 title</rux-tab>
<rux-tab id="tab-id-2">Top 2 title</rux-tab>
<rux-tab id="tab-id-3">Top 3 title</rux-tab>
</rux-tabs>
<rux-tab-panels aria-labelledby="tab-set-id-1">
<rux-tab-panel id="t1content" aria-labelledby="tab-id-1">Top Tab 1 content</rux-tab-panel>
<rux-tab-panel id="t2content" aria-labelledby="tab-id-2">Top Tab 2 content</rux-tab-panel>
<rux-tab-panel id="t3content" aria-labelledby="tab-id-3">Top Tab 3 content</rux-tab-panel>
</rux-tab-panels> …
```
=> Mj 4519 tab issue

.changeset/clever-melons-collect.md, packages/web-components/src/components/rux-dialog/readme.md, packages/web-components/src/components/rux-dialog/rux-dialog.tsx, packages/web-components/src/components/rux-dialog/test/index.html, packages/web-components/src/stories/dialog.stories.mdx, packages/web-components/tests/dialog.spec.ts
This re-adds the `click-to-close` prop that went missing somehow. Look for it on milk cartons I guess.
Also changes the prop names of `modalTitle` and `modalMessage` to `header`, `message`.
Adds tests and updates SB as well.
prop name changes -> https://rocketcom.atlassian.net/browse/ASTRO-4457
click-to-close prop -> https://rocketcom.atlassian.net/browse/ASTRO-4530
The click-to-close prop keeps dialog inline with our compliance while also providing external users the ability to customize it.
The prop names needed to be changed to reflect the renamed component. 
I noticed that on `main`'s version of dialog, the tabbing through buttons on the dialog works great and shows which button is focused. The `next` version does not. The keyboard presses still work but tabbing doesn't seem to be. 
I …
=> Mj 4530 click to close

packages/web-components/src/common/functional-components/FormFieldMessage/FormFieldMessage.tsx, packages/web-components/src/components.d.ts, packages/web-components/src/components/rux-checkbox/rux-checkbox.scss, packages/web-components/src/components/rux-checkbox/rux-checkbox.tsx, packages/web-components/src/components/rux-checkbox/test/__snapshots__/rux-checkbox.spec.tsx.snap, packages/web-components/src/components/rux-checkbox/test/index.html, packages/web-components/src/utils/utils.ts
Removed the hasLabelSlot State and refactored the conditional rendering of the label "prop" vs the label "slot". 
Recommending the removal of the label "prop" in v7. Added the "Deprecated" tag in the prop comments. 
Removed dead classes.
[Ticket 4225](https://rocketcom.atlassian.net/browse/ASTRO-4225)
[Ticket 4492](https://rocketcom.atlassian.net/browse/ASTRO-4492)
This change eliminates the multiple renders when the checkbox is checked or unchecked causing the hasLabelSlot boolean state to switch back to false when it should be true. This is the root cause of the 2 known bug tickets.
=> Bk 4225 4492 fix label bugs

.changeset/fast-panthers-kneel.md, packages/web-components/package-lock.json, packages/web-components/src/components/rux-tree-node/rux-tree-node.tsx, packages/web-components/src/components/rux-tree-node/test/__snapshots__/rux-tree-node.spec.tsx.snap, packages/web-components/src/components/rux-tree/test/index.html
Add parts to rux-tree-node to replace deprecated css custom properties as a means of styling 
[ASTRO-3658](https://rocketcom.atlassian.net/browse/ASTRO-3658)
some css custom properties were deprecated, leading to a new way of thinking about how one would style the web components. To that end, these shadow parts are meant to return styling. ability to developers
- [] This PR adds or removes a Storybook story.
=> Km 3658 rux tree 6 add parts

packages/web-components/src/components/rux-dialog/rux-dialog.tsx, packages/web-components/src/components/rux-menu-item/rux-menu-item.tsx, packages/web-components/src/components/rux-pop-up-menu/rux-pop-up-menu.tsx, packages/web-components/src/components/rux-push-button/rux-push-button.tsx, packages/web-components/src/components/rux-radio-group/rux-radio-group.tsx, packages/web-components/src/components/rux-segmented-button/rux-segmented-button.tsx, packages/web-components/src/components/rux-switch/rux-switch.tsx, packages/web-components/src/components/rux-tabs/rux-tab-panels/rux-tab-panels.tsx, packages/web-components/src/components/rux-tabs/rux-tabs.tsx, packages/web-components/src/components/rux-timeline/rux-time-region/rux-time-region.tsx, packages/web-components/src/components/rux-tree-node/rux-tree-node.tsx
Update all event comments which emit data when fired to look for that data on the event.detail
https://rocketcom.atlassian.net/browse/ASTRO-4543
This change is help devs understand where data is emitted when an event is fired which include data.
=> docs(next): update api to reference data emitted on the event.detail

packages/web-components/src/components/rux-dialog/rux-dialog.tsx, packages/web-components/src/components/rux-menu-item/rux-menu-item.tsx, packages/web-components/src/components/rux-modal/rux-modal.tsx, packages/web-components/src/components/rux-push-button/rux-push-button.tsx, packages/web-components/src/components/rux-radio-group/rux-radio-group.tsx, packages/web-components/src/components/rux-segmented-button/rux-segmented-button.tsx, packages/web-components/src/components/rux-switch/rux-switch.tsx, packages/web-components/src/components/rux-tabs/rux-tab-panels/rux-tab-panels.tsx, packages/web-components/src/components/rux-tabs/rux-tabs.tsx, packages/web-components/src/components/rux-timeline/rux-time-region/rux-time-region.tsx, packages/web-components/src/components/rux-tree-node/rux-tree-node.tsx
Update all event comments which emit data when fired to look for that data on the event.detail
https://rocketcom.atlassian.net/browse/ASTRO-4543
This change is help devs understand where data is emitted when an event is fired which include data.
=> docs(main): update api to reference data emitted on the event.detail

.changeset/smooth-parents-flow.md, packages/web-components/src/components.d.ts, packages/web-components/src/components/rux-select/rux-select.scss, packages/web-components/src/components/rux-select/test/index.html
Modifying the spacing of the `rux-select` component to match the updated Figma designs.
[JIRA-3863](https://rocketcom.atlassian.net/browse/ASTRO-3863)
The `rux-select` component had as many pixel and rem values converted to spacing tokens as were in the .scss file. Some of the values were also modified to exactly match the design specifications, specifically padding values, and the border attributes were changed to box-shadow in line with our other recent changes so that the border does not take up computed space. This allows the overlay of the Figma design and the code to more closely match. The caret arrow was also changed to match the Figma design.
Our code differed slightly from what is currently in Figma and we no longer want to use hard-coded values where design tokens can be used.
=> Fm 3863 select menu spacing

.changeset/unlucky-foxes-pretend.md, packages/web-components/.storybook/preview-head.html, packages/web-components/src/common/functional-components/FormFieldMessage/form-field-message.scss, packages/web-components/src/components/rux-checkbox-group/rux-checkbox-group.scss, packages/web-components/src/components/rux-clock/rux-clock.scss, packages/web-components/src/components/rux-input/rux-input.scss, packages/web-components/src/components/rux-notification/rux-notification.scss, packages/web-components/src/components/rux-push-button/rux-push-button.scss, packages/web-components/src/components/rux-radio-group/rux-radio-group.scss, packages/web-components/src/components/rux-segmented-button/rux-segmented-button.scss, packages/web-components/src/components/rux-select/rux-select.scss, packages/web-components/src/components/rux-textarea/rux-textarea.scss, packages/web-components/src/components/rux-tree-node/rux-tree-node.scss, packages/web-components/src/global/_variables.scss, packages/web-components/src/stories/notification.stories.mdx
implements recent 6.0 light theme changes 
* tree node's arrow fill color on hover
* tree node's border left when selected
* fixes regression in segmented button background color on hover
* push button's text color 
* push button's icon color 
* adds borders around notification 
* fixes regression in clock border color
* swaps red-500 with 700 for errors 
ASTRO-4594
6.0 is already using a subset of the new 7.0 naming convention. Some of these changes require new tokens, but instead of publishing a whole separate, short-lived release of our 6.0-flavored tokens, I just created the ones that we needed locally in the vars.scss. 
Anything that uses an svg as a background image (FormFieldMessage error icon and checkbox) doesn't theme switch bc we can't use css custom props when an svg is …
=> Light theme updates

.changeset/late-cheetahs-agree.md, packages/web-components/src/components/rux-input/rux-input.scss
Updates rux-input scss to apply the correct placeholder text color. 
https://rocketcom.atlassian.net/browse/ASTRO-4605
https://github.com/RocketCommunicationsInc/astro/issues/738
input's placeholder text was not the correct color. Refactored the specificity of `::placeholder` a bit to fix this.
=> Mj 4605 placeholder text

packages/astro-uxds/_content/migration.md, packages/web-components/CHANGELOG.md, packages/web-components/CSS-Prop-Migration.md, packages/web-components/src/components/rux-slider/rux-slider.scss
Restores the before thumb height css custom prop on slider.
=> feat: restore before thumb prop

.changeset/angry-houses-suffer.md, packages/web-components/CHANGELOG.md, packages/web-components/src/components.d.ts, packages/web-components/src/components/rux-log/rux-log.scss, packages/web-components/src/components/rux-log/rux-log.tsx, packages/web-components/src/components/rux-log/test/__snapshots__/rux-log.spec.tsx.snap, packages/web-components/src/components/rux-log/test/index.html
rux-log spacing changes, add spacing tokens and align with Astro 7.0 design
[ASTRO-3853](https://rocketcom.atlassian.net/browse/ASTRO-3853)
Part of the astro 7.0 spacing initiative!
I ran into a couple of issues lining up figma specs and the rux-log here. I'll do my best to document them here but if you have questions please ask!
1. This isn't exactly an issue, but I wanted to note that the table header and table body row heights are different (in figma) for rux-log than they are in rux-table even though rux-log is basically a rux-table with data in it. I've stuck to figma design here, but wanted to make a note.
2. In order to maintain simplicity, you'll notice that the log columns don't line up 100% with figma. This is because cells have 8px padding to the left and the right and the …
=> Km 3853 rux log update spacing

.changeset/purple-apes-promise.md, packages/web-components/src/components/rux-input/rux-input.scss, packages/web-components/src/components/rux-input/test/index.html
In <rux-input type="search"> I flipped the search icon around to align to Astro 7.0 design. I also cleaned up some of the figma testing in /test/ page
[ASTRO-4631](https://rocketcom.atlassian.net/browse/ASTRO-4631)
Aligns to Astro 7.0 design in figma, and also it was just driving me crazy.
=> new magnifying icon and size

packages/angular-workspace/projects/angular/src/directives/proxies-list.ts, packages/react/src/react-component-lib/createComponent.tsx, packages/web-components/docs.d.ts, packages/web-components/package-lock.json, packages/web-components/package.json, packages/web-components/src/components.d.ts, packages/web-components/src/components/rux-slider/rux-slider.tsx, packages/web-components/tests/accordion.spec.ts, packages/web-components/tests/slider.spec.ts
Bumps the `@stencil/react-output-target` to latest
Bumps `@stencil/core` to latest. 
https://rocketcom.atlassian.net/browse/ASTRO-4598
=> chore: bump react-output-target, stencil, ran builds

packages/web-components/src/components/rux-push-button/rux-push-button.scss
removes the unused pushbutton-background-color css custom prop
fixes an issue where checked state became inline flex 
ASTRO-4363
=> fix(push-button): rm custom prop and inline flex

.changeset/metal-fishes-share.md, packages/web-components/src/components/rux-dialog/rux-dialog.tsx, packages/web-components/tests/dialog.spec.ts
The `e.detail` emitted by `rux-dialog` would not reset to it's default value after the event was emitted. Because of this, if you opened the dialog, clicked confirm, it would emit true. If you opened that same dialog again and clicked off to close it, it would emit true again even though no choice was made. 
Added a test for this case.
https://rocketcom.atlassian.net/browse/ASTRO-4635
Fixes an inconsistency in the event detail of dialog.
=> fix(dialog): event detail now correct after reopening same modal

packages/web-components/src/components/rux-select/rux-select.scss, packages/web-components/src/stories/select.stories.mdx
Some random style cleanups on select.
- Options that are disabled no longer change color on hover
- Reverted box-shadow borders back to border in order to fix issue in multi-select where border did not encompass the scrollbar 
- removed a random, deprecated css custom prop from the scrollbar styles. 
- Fixed the `multiple` attribute not reflecting properly in SB examples 
https://rocketcom.atlassian.net/browse/ASTRO-4643
styling inconsistencies
=> style(select): updated borders, updated option hover color when disabled

.changeset/shiny-falcons-hope.md, packages/web-components/src/common/functional-components/MonitoringLabel.tsx, packages/web-components/src/components/rux-monitoring-icon/test/__snapshots__/rux-monitoring-icon.spec.tsx.snap, packages/web-components/src/components/rux-monitoring-progress-icon/test/__snapshots__/rux-monitoring-progress-icon.spec.tsx.snap
Moves a the monitoring-label up a level to the parent div of the label span.
https://rocketcom.atlassian.net/browse/ASTRO-4650
Tom noticed that you can't change the label off of `overflow: hidden`. This fixes that.
The part wasn't helpful at all. Moved it to where it is helpful.
=> Mj 4650 monit icon part

packages/web-components/src/components/rux-tabs/rux-tab/rux-tab.scss
A disabled tab will no longer change text color on hover.
=> fix(tab): hover color on disabled tab

packages/starter-kits/angular-starter/package.json, packages/starter-kits/react-starter/package.json, packages/starter-kits/svelte-starter/package.json, packages/starter-kits/vue-starter/package.json, packages/web-components/src/stories/popup.stories.mdx
Updates cherry picking section in popup to include all relevant components.
Bumps the `@astrouxds/astro-web-components` version in all starter kits to `^7.0.0`. Also bumps the `astrouxds/angular` and `astrouxds/react` deps in ang/react starter kits to `^7.0.0`
https://rocketcom.atlassian.net/browse/ASTRO-4651
=> docs(popup): updated cherry picking section

packages/starter-kits/react-starter/src/App.js, packages/starter-kits/svelte-starter/public/index.html, packages/starter-kits/vue-starter/public/index.html, packages/web-components/src/stories/astro-uxds/welcome/vue.stories.mdx
Cleans up starter-kits for 7.0
- React
- Changes `<RuxProgress />` comp to `<RuxIndeterminateProgress />`
- Vue and Svelte
- Updates `public/index.html` to use the correct roboto font. 
- Updates Vue story to have correct font in CDN code snippet
https://rocketcom.atlassian.net/browse/ASTRO-4665
Matches 7.0 now
=> Mj 4665 starter kits

packages/web-components/src/stories/astro-sandboxes/forms/angular/basic-form/package.json, packages/web-components/src/stories/astro-sandboxes/forms/react/basic/package.json, packages/web-components/src/stories/astro-sandboxes/forms/react/validation/package.json, packages/web-components/src/stories/astro-sandboxes/forms/svelte/basic/package.json, packages/web-components/src/stories/astro-sandboxes/forms/svelte/validation/package.json, packages/web-components/src/stories/astro-sandboxes/forms/vue/basic/package.json, packages/web-components/src/stories/astro-sandboxes/forms/vue/validation/package.json
Updates sandbox form examples to use latest astro version (^7.0.1)
https://rocketcom.atlassian.net/browse/ASTRO-4664
Makes our form examples on SB up to date.
=> docs: update form sandboxes to use 7.0

.changeset/polite-pianos-allow.md, packages/web-components/src/components/rux-checkbox/rux-checkbox.scss
Changes --disabled-opacity token to --opacity-disabled in rux-checkbox
I also ran a general search for --disabled-opacity to ensure that there weren't other instances. I didn't find any
[ASTRO-4686](https://rocketcom.atlassian.net/browse/ASTRO-4686)
I just noticed the token was wrong and thus it wasn't giving checkbox standard opacity for disabled elements.
=> opacity token correction

.changeset/selfish-plants-study.md, packages/web-components/src/components/rux-pop-up/rux-pop-up.scss
An [issue](https://github.com/RocketCommunicationsInc/astro/issues/812) came in that showed rux-pop-up fell under some of our normal components which isn't what a user would expect. So I added a z-index to have it overlay components that are below it in code.
Here is the issue as reported on GitHub: [issue 812](https://github.com/RocketCommunicationsInc/astro/issues/812)
It now falls over every component we have, EXCEPT for rux-dialog and rux-classification-marking. I understand that there is an important compliance item which requires classification markings to overlay all other things.
Changes visibility to be more inline with user expectations.
=> added a z-index to rux-popup

.changeset/tidy-moons-suffer.md, packages/web-components/src/components/rux-textarea/rux-textarea.scss, packages/web-components/src/components/rux-textarea/rux-textarea.tsx, packages/web-components/src/components/rux-textarea/test/__snapshots__/rux-textarea.spec.tsx.snap, packages/web-components/src/components/rux-textarea/test/index.html
Made a change to rux-textarea that reverts the code layout back from
```<div class="wrapper">
<textarea></textarea>
</div>```
To a simpler <textarea></textarea>
[ASTRO-4688](https://rocketcom.atlassian.net/browse/ASTRO-4688)
[ASTRO-4691](https://rocketcom.atlassian.net/browse/ASTRO-4691)
[815](https://github.com/RocketCommunicationsInc/astro/issues/815)
[814](https://github.com/RocketCommunicationsInc/astro/issues/814)
While originally, this change was made to combat a textarea bug in safari, the unintended consequence was to make rux-textarea less intuitive and in some cases less accessible for developers. So we are rolling back that change and things should work as they once did.
=> Km 4688 rux textarea revert wrapper

.changeset/light-teachers-fold.md, packages/web-components/src/components/rux-tabs/rux-tab-panels/rux-tab-panels.tsx, packages/web-components/src/components/rux-tabs/rux-tabs.tsx, packages/web-components/src/index.html, packages/web-components/tests/tabs.spec.ts
Fixes an issue where tabs could not be dynamically added. 
- new tabs no longer retain selected state when they shouldn't 
- new panel content no longer shows when it shouldn't 
https://rocketcom.atlassian.net/browse/ASTRO-4719
Dynamically added rux-tabs were resulting in unexpected results.
=> fix(tabs): allow for dynamic tab additions

packages/astro-uxds/_content/components/global-status-bar.md, packages/astro-uxds/_includes/home.template.njk
An image on https://www.astrouxds.com/components/global-status-bar/ page was broken. It turned out that the src was just incorrect so I directed it to the proper image.
While I was in there I also took the opportunity to update the Events on the home page. They do not programmatically update.
[ASTRO- 4742](https://rocketcom.atlassian.net/browse/ASTRO-4742)
link fix
=> correct image link

packages/starter-kits/vue-starter/package.json, packages/web-components/src/stories/astro-uxds/welcome/vue.stories.mdx
vue is dumb and chirps at you if you use `slot` now
=> docs(vue): deprecated slot eslint rule

packages/astro-uxds/_content/components/_readme.md
This updates the web components documentation to update a dated reference to Edge support.
There is no ticket.
It inaccurately reflects the current state of the web.
☝️ None of these are related to the change.
=> docs: Fix a dated reference to Edge support

.github/ISSUE_TEMPLATE/config.yml
This will redirect users who are opening a feature request issue to the github discussions instead. 
https://rocketcom.atlassian.net/browse/ASTRO-4818
=> docs: redirect new feat reqs to github disucssions

.changeset/blue-experts-tan.md, packages/web-components/src/components.d.ts, packages/web-components/src/components/rux-menu-item/rux-menu-item.scss, packages/web-components/src/components/rux-menu-item/rux-menu-item.tsx
This PR restores a few attributes on menu item from 6.0: `href`, `rel`, `target` and `download.`
These were removed in 7.0 intentionally but weren't properly documented. The intention was that you would use the slot instead if you wanted an ahref:
```
<rux-menu-item>
<a href="#">whatup</a>
</rux-menu-item>
```
vs.
```
<rux-menu-item href="#>
whatup
</rux-menu-item>
```
After closer inspection, you would need to manually have to tinker with the padding otherwise the link would only trigger if you clicked exactly on the a element. Instead we decided to keep the 6.0 API.
ASTRO-4811
https://github.com/RocketCommunicationsInc/astro/issues/862
=> fix(menu-item): restore 6.0 props

.changeset/eighty-moles-rule.md, packages/angular-workspace/package-lock.json, packages/angular-workspace/projects/angular/package-lock.json, packages/react/package-lock.json, packages/web-components/src/components/rux-input/rux-input.tsx, packages/web-components/tests/input.spec.ts
Removes the `autocomplete` attribute from rux-input due to it never taking effect. 
This isn't a breaking change because the attribute never worked in the first place; it only had the attribute in the shadow dom, but it wasn't functioning. 
https://rocketcom.atlassian.net/browse/ASTRO-4825
https://github.com/RocketCommunicationsInc/astro/issues/877
Issue was raised here. Fix for issue will be implemented at a later date. 
We are looking into fixes for this in future, but it has been deprioritized for now. 
We don't want to provide an attribute that doesn't actually work.
=> refactor(input): removed autocomplete attr

.changeset/shaggy-days-bow.md, packages/web-components/src/components.d.ts, packages/web-components/src/components/rux-select/rux-select.scss, packages/web-components/src/components/rux-select/test/index.html
Changed rux-select so that long options no longer fall over the drop down arrow.
[ASTRO-4820](https://rocketcom.atlassian.net/browse/ASTRO-4820)
https://github.com/RocketCommunicationsInc/astro/issues/722
When rux-select contains longer options they could fall over the drop down menu arrow. This fix applies some extra padding to account for the size of the drop down arrow in each size of rux-select. Because rux-select uses box-sizing: border-box it won't change the actual of rux-select itself.
=> change right padding to include dropdown indicator

.github/workflows/pull-request.yml
Previously, our github action e2e tests would only run a stencil build if the package.json file had changed. 
This has been changed to run a build on every PR.
https://rocketcom.atlassian.net/browse/ASTRO-4842
GA will no longer pass if there are any build errors.
=> test(ga): always run build as part of test setup

packages/web-components/src/components/rux-timeline/rux-time-region/rux-time-region.scss
Added borders to partial events even when selected. The borders are color/palette/neutral/1000 as they appear on the figma specs. This allows users to know that selected partial events are still partial events. 
[ASTRO-4844](https://rocketcom.atlassian.net/browse/ASTRO-4844)
Previously, when a partial timeline event was selected it would lose the dashed left/right border which indicated it as a partial event. Adding them back in a neutral color when selected, brings back the visual queue.
=> fix(rux-timeline): added left/right/both border to selected partial events

.changeset/flat-cups-sit.md, packages/web-components/src/components/rux-pop-up/rux-pop-up.tsx
The `strategy` prop on rux-pop-up was not being applied correctly. This now applies the correct `position: ` to the pop-up. 
This fixes an issue where a pop-up inside a parent that had `position: absolute; overflow: hidden` would hide the pop-up. 
https://rocketcom.atlassian.net/browse/ASTRO-4867
Pop-up was being hidden when the above conditions where being met. 
This still does not fix an issue where a `transform` on a parent will still hide some or all of the pop-up. This is due to `transform` creating it's own stacking context, and thus the pop-up gets rendered behind it.
=> Mj 4867 pop up overflow

.changeset/heavy-kings-smell.md, packages/web-components/src/components/rux-notification/rux-notification.tsx, packages/web-components/tests/notification.spec.ts
This is a followup to the rux-notification issue [#854](https://github.com/RocketCommunicationsInc/astro/pull/854) while I still believe that the ultimate solution is to remove the message prop, @micahjones13 has come up with a brilliant interim solution that is not a breaking change and does fix the issue. I've basically taken his work on rux-dialog and emulated it here. :) 
[ASTRO-4780](https://rocketcom.atlassian.net/browse/ASTRO-4780)
[#904](https://github.com/RocketCommunicationsInc/astro/pull/904)
Thanks Micah!
This will allow the message prop to render if the default slot isn't filled. EVEN if there is another slot inside the component that is being used.
=> emulate changes micah made to rux-dialog

.changeset/clever-hounds-watch.md, packages/angular-workspace/projects/angular/src/directives/proxies-list.ts, packages/web-components/package-lock.json, packages/web-components/src/stories/icon-and-symbols.stories.mdx
The Storybook story for `rux-icon` was incorrectly showing that it had a label prop. This has been removed from its story.
[ASTRO-4872](https://rocketcom.atlassian.net/browse/ASTRO-4872)
https://github.com/RocketCommunicationsInc/astro/issues/907
=> (fix rux-icon): Removing incorrect label prop from rux-icon storybook

.changeset/eighty-actors-behave.md, packages/web-components/src/components/rux-monitoring-icon/rux-monitoring-icon.scss, packages/web-components/src/components/rux-monitoring-icon/test/index.html, packages/web-components/src/components/rux-monitoring-progress-icon/rux-monitoring-progress-icon.scss, packages/web-components/src/components/rux-push-button/rux-push-button.scss, packages/web-components/src/components/rux-push-button/test/index.html
An issue was discovered wherein if `rux-monitoring-icon` or `rux-monitoring-progress-icon` were wrapping in `display: grid` the icons pieces and the label pieces of the component would not be aligned. This PR fixes that issue. Another issue was discovered in `rux-push-button` that has been fixed as well where the cursor turning to pointer would fall outside of the bounds of the button itself if a specific width was set on the component.
[ASTRO-4875](https://rocketcom.atlassian.net/browse/ASTRO-4875)
=> (fix): monitoring-icon and monitoring-progress-icon display grid issue and push button cursor issue

packages/web-components/src/stories/accordion-item.stories.mdx, packages/web-components/src/stories/accordion.stories.mdx, packages/web-components/src/stories/button-group.stories.mdx, packages/web-components/src/stories/checkbox-group.stories.mdx, packages/web-components/src/stories/checkbox.stories.mdx, packages/web-components/src/stories/datetime.stories.mdx, packages/web-components/src/stories/indeterminate-progress.stories.mdx, packages/web-components/src/stories/input.stories.mdx, packages/web-components/src/stories/menu-item-divider.stories.mdx, packages/web-components/src/stories/menu-item.stories.mdx, packages/web-components/src/stories/menu.stories.mdx, packages/web-components/src/stories/popup.stories.mdx, packages/web-components/src/stories/radio-group.stories.mdx, packages/web-components/src/stories/radio.stories.mdx, packages/web-components/src/stories/segmented-button.stories.mdx, packages/web-components/src/stories/slider.stories.mdx, packages/web-components/src/stories/table.stories.mdx, packages/web-components/src/stories/tag.stories.mdx, packages/web-components/src/stories/textarea.stories.mdx, packages/web-components/src/stories/tree-node.stories.mdx, packages/web-components/src/stories/tree.stories.mdx
Update default imports to named imports since that's what the files actually export (at least in 6.x, haven't updated to 7.x yet)
=> Update cherry picking docs

.changeset/warm-rice-divide.md, packages/web-components/src/components/rux-segmented-button/rux-segmented-button.scss
Adds `cursor: pointer` to an enabled rux-segmented-button.
I wanted to also add `pointer: not-allowed` to a disabled seg button, but because we're setting `pointer-events: none` on `:host[disabled]`, it doesn't work. We'd have add a wrapper or something and set that to `cursor: not-allowed`. 
https://rocketcom.atlassian.net/browse/ASTRO-4877
=> style(seg-btn): added pointer cursor

.changeset/chilled-goats-argue.md, packages/web-components/src/components/rux-select/rux-select.tsx
Adds `title` attribute reflection to `rux-option` and `rux-option-group`. 
https://rocketcom.atlassian.net/browse/ASTRO-4892
https://github.com/RocketCommunicationsInc/astro/issues/930
This does not add any new props, but simply reflects the `title` attribute if it exists. 
Github issue 
Title attributes should be avoided if possible, but there is no other way to get a tooltip on our rux-select. 
Does not work using microsoft edge.
=> fix(select): options now reflect title attr

package.json
Loosens the restrictions in `package.json` so that both Node v16 and Node v18 are usable. It also allows all versions `npm` v8 in both Node v16 and Node v18.
=> Loosen package.json restrictions

CONTRIBUTING.md, package.json, packages/angular-workspace/package-lock.json, packages/angular-workspace/projects/angular/package-lock.json, packages/angular-workspace/projects/angular/src/directives/proxies-list.ts, packages/react/package-lock.json
This adds any remaining changes on a clean install of the project.
- Update package-lock.json files.
- Clear excess `//@ts-nocheck` from `proxies-list.ts`. The underlying issue can be solved at some later point.
- Remove special Apple Silicon instructions for `puppeteer`, which was removed in a previous commit.
- Prevent unexpected file diffs after `npm run build` by running `npx pretty-quick` during `postbuild`.
=> Add post-install diffs

.changeset/itchy-humans-leave.md, packages/web-components/src/components/rux-tag/rux-tag.tsx, packages/web-components/src/components/rux-tag/test/index.html
I tested rux-tag to see if the conditional rendering of the default slot would break if a slot was added programmatically after first render. It did, so I solved this in a similar way to rux-notification. I added a slot change handler, and a new state which holds whether or not rux-tag has a slot. It then conditionally renders the Status prop string.
As an added benefit, these changes bring the code more inline with our other components.
[ASTRO-4890](https://rocketcom.atlassian.net/browse/ASTRO-4890)
I know that we are going to be looking at rux-tag against soon these changes may also help with the future enhancements.
When a slot was added after the component had initially been rendered it would not appear properly. This has to do with the nature of conditionally rendering slots in …
=> remove conditional rendering of slot for rux-tag

.changeset/lemon-buckets-leave.md, packages/web-components/src/components/rux-pop-up/rux-pop-up.tsx
Moved aria-hidden on rux-pop-up to describe the pop up itself rather than the entire component.
[ASTRO-4908](https://rocketcom.atlassian.net/browse/ASTRO-4908)
When the pop-up container was hidden on rux-pop-up aria-hidden = true was being applied to the entire component which made it impossible for keyboard users to tab into the button/trigger for the pop up. Effectively this made the component inaccessible to keyboard users indefinitely.
=> fix(rux-pop-up)

packages/web-components/src/components/rux-segmented-button/rux-segmented-button.scss, packages/web-components/src/global/_variables.scss
This is the PR for segmented buttons. I had to make them tab enabled. in order to accomplish this I changed <input> from display: none to absolutely positioned within the button with an opacity of 0. This way it can still be tabbed into and the proper button segment takes on the focus state.
Part of focus state first sweep
One problem I'm seeing is that tabbing between segmented buttons does not work. The internals work fine, arrow keys will determine which button is selected and you can tab back to the one that you had selected.
That said, if you have two segmented buttons in a row you cannot tab from one to the next. HOWEVER, if you have two segmented buttons that are separated by something else with a tab index then you can tab between all items.
=> make segmented buttons ttab-able and add focus

packages/web-components/src/components/rux-tabs/rux-tab/rux-tab.scss, packages/web-components/src/components/rux-tabs/rux-tab/rux-tab.tsx, packages/web-components/src/components/rux-tabs/rux-tabs.tsx, packages/web-components/src/components/rux-tabs/test/index.html, packages/web-components/src/components/rux-tabs/test/tabs.spec.ts
Borrowed some code from Mark for the keyboard functionality of tabs, and then inserted my own roving tab index logic. Now tabs work as they should. They currently do not automatically activate on focus but a keyboard user can use the arrow keys to select the appropriate tab and hit enter to activate it.
[ASTRO-4952](https://rocketcom.atlassian.net/browse/ASTRO-4952)
Part of focus state work.
tab keyboard control didn't work as one would expect. now it does.
I am sick. please look at code and critique my potato brain.
=> Fix keyboard functionality for rux-tabs

packages/web-components/src/components/rux-notification/rux-notification.scss, packages/web-components/src/components/rux-notification/rux-notification.tsx
Rux-notification could not be focused since it did not have a tab index. Added that and keyboard controls and then our focus outline state.
[ASTRO-5078](https://rocketcom.atlassian.net/browse/ASTRO-5078)
Focus state general tweaking
We need to revisit some of our components that use overflow:hidden in any way. Sometimes this cuts off focus state which isn't great. In notification specifically we should revisit the idea that notifications should be truncated with no way to see the rest of the notification.
=> add focus state for close button/keyboard control

packages/web-components/src/components/rux-notification/rux-notification.scss, packages/web-components/src/components/rux-notification/test/basic/index.html
adjusts padding on notification to allow for focus state when links are slotted
=> fix(notification): accomodate text focus styles

packages/web-components/src/stories/card.stories.mdx
Update storybook for rux-card to remove the hamburger icon in full example.
[ASTRO-5084](https://rocketcom.atlassian.net/browse/ASTRO-5084)
The hamburger icon wasn't interactive though, because of the nature of hamburger icons it seemed like it should be. Adding interactive code to it would have made the sample annoyingly long so I removed the icon instead.
=> remove menu icon since it was not interactive

packages/web-components/src/stories/popup.stories.mdx
Changes pop-up storybook entry to make the menu items within pop-up interactive. This way they can take on focus state when tabbed into.
[ASTRO-5067](https://rocketcom.atlassian.net/browse/ASTRO-5076)
Part of the Astro focus state initiative!
=> Km 5076 pop up storybook changes - focus state

.changeset/wild-pandas-walk.md, packages/web-components/package.json, packages/web-components/src/components/rux-clock/rux-clock.scss
Updates the `hide-labels` version of clock to not include a fixed height. 
https://rocketcom.atlassian.net/browse/ASTRO-5103
=> style(clock): fixed height no longer applies to hide-label version

.changeset/modern-items-refuse.md, packages/web-components/src/components/rux-checkbox/rux-checkbox.scss
The <input> element in the Shadow DOM of rux-checkbox is opacity:0 and position: absolute. However, since no parent element was position:relative, the <input> was just kind of going wherever it felt like on the page and wreaking havoc. I added position:relative to the label element which contains both our custom input and the actual <input> in order to contain it.
[ASTRO-5148](https://rocketcom.atlassian.net/browse/ASTRO-5148)
Minor bug fix to address some layout abnormalities when using many rue-checkboxes, as you might in a table of events.
=> fix(rux-checkbox): fix bug where the invisible <input> component was interfering with certain layouts

.changeset/itchy-cows-travel.md, packages/web-components/src/components/rux-notification/rux-notification.scss, packages/web-components/src/components/rux-notification/rux-notification.tsx
The default close button on rux-notification did not have a hand pointer when hovered to indicate that it can be activated. It should, so one was added.
[ASTRO-5069](https://rocketcom.atlassian.net/browse/ASTRO-5069)
=> add pointer to close icon on rux-notification

.changeset/stupid-suits-attend.md, packages/web-components/src/components/rux-monitoring-icon/rux-monitoring-icon.scss, packages/web-components/src/components/rux-monitoring-icon/test/index.html
This is a minor tweak to the monitoring icon work Frances did a couple of weeks ago. Despite her excellent efforts, the GSB was still cursing off part of the notifications badge on the monitoring icon.
I changes the border around the monitoring icon from outset to inset so that the calculations used to size the notification badge could take the whole box+border into account. I ran VRTs and adjusted the badge accordingly.c
[Astro-5149](https://rocketcom.atlassian.net/browse/ASTRO-5149)
Makes the GSB and rux-monitoring icon play nice together.
=> Fix(rux-monitoring-icon) border chopped off by gsb

.github/workflows/pull-request.yml, packages/web-components/package.json
This is a ci/cd change only.
Improves GA time with caching of node_modules and build files 
Adds new VRT job 
Splits e2e tests out into own job. 
Adds new (old) setup job. 
The setup job will always run a `npm run build` from root to ensure that the project's packages build with the new code. 
https://rocketcom.atlassian.net/browse/ASTRO-5240
=> ci/cd: Add VRTs to github actions

packages/web-components/netlify.toml
This PR makes it possible for the `astro-stencil` netlify deploy preview to show our `src/index.html`. This way we can view sample code without having to pull down the branch.
To accomplish this, I remove the `netlify.toml` and changed the params of each deploy preview on the netlify site. This `.toml` was way out of date anyway. The astro preview (the storybook one) remains unchanged.
In the future, I want this to show all the `component/test/basic` pages, but that'll require some more work. This is more of a quick win. 
https://rocketcom.atlassian.net/browse/ASTRO-5226
Allows for quick previews of example code.
=> refactor: src/index deploy previews

.changeset/proud-wolves-divide.md, packages/web-components/src/components/rux-container/rux-container.scss, packages/web-components/src/components/rux-container/rux-container.tsx
Added a 'container' part to the outermost div of the rux-container. I also added scrollbar stylings.
[ASTRO-5331](https://rocketcom.atlassian.net/browse/ASTRO-5331)
It was brought to our attention by @brikiernan that a very common use case for containers was to hold scrollable content. It was difficult to style the height of rux-container in such a way that would allow the inner parts to align properly and the body to scroll. Adding part='container' to the surrounding div should allow for more flexibility and easier access to change height properties/add Flexbox or grid stylings for layout.
=> Km 5331 add container part to rux-container

packages/web-components/src/components/rux-dialog/test/dialog.spec.ts
adds `page.waitForChanges` to two dialog tests that would sometimes fail. 
https://rocketcom.atlassian.net/browse/ASTRO-5329
=> test(dialog): added waitForChanges to prevent dialog flake

packages/web-components/src/components/rux-option/rux-option.tsx, packages/web-components/src/components/rux-select/test/select.spec.ts, packages/web-components/src/index.html
Fixes an issue where the rux-option wouldn't update on select when the disabled prop was dynamically changed.
I left some code in the `src/index.html` to help the review process. Checkout the astro-stencil deploy preview to see that. I'll remove it before merge. 
Adds tests to cover the dynamic addition of label, value and disabled props to rux-option. 
https://rocketcom.atlassian.net/browse/ASTRO-5699
https://github.com/RocketCommunicationsInc/astro/issues/1075
=> fix(rux-option): added watch to disabled prop

.changeset/chatty-avocados-exist.md, packages/web-components/src/components/rux-checkbox/rux-checkbox.scss, packages/web-components/src/components/rux-checkbox/rux-checkbox.tsx, packages/web-components/src/components/rux-checkbox/test/checkbox.spec.ts, packages/web-components/src/components/rux-segmented-button/rux-segmented-button.scss, packages/web-components/src/components/rux-segmented-button/rux-segmented-button.tsx
We had a couple of elements that were using :focus-within to display focus originally. However, that sometimes displayed focus when none was intended to be displayed.
So, in a previous quick-fix we changed the selector to :has(element:focus-within). That worked well, except that not all browsers support the :has selector yet. (Firefox does not, for example).
In this fix, I removed the :has selector from rux-segmented-button and rux-checkbox in favor of a small onFocus and onBlur script that programmatically adds a focused state to the elements that require focus styling. 
[ASTRO-5268](https://rocketcom.atlassian.net/browse/ASTRO-5268)
I had to apply similar but different solutions to checkbox and segmented button. The theory is the same but in segmented button I had to select the correct …
=> fix(focus) Remove :has selector from components that were previously using :focus-within

packages/web-components/package.json
Adds the homepage and repository fields to `package.json` on `web-components`
I put the homepage as our storybook, since that's the most dev related homepage. If we want to change that to astrouxds.com that's fine too 
Was noticed by Sasha and brought up during dev bookclub meeting
Allows for our npm page to have links to our SB and github repo
=> docs: add homepage and repository field for web-components

.changeset/stale-hotels-remain.md, .changeset/witty-jeans-grow.md, packages/web-components/src/components.d.ts, packages/web-components/src/components/rux-select/rux-select.tsx, packages/web-components/src/components/rux-select/test/select.spec.ts, packages/web-components/src/components/rux-textarea/rux-textarea.tsx, packages/web-components/src/components/rux-textarea/test/textareas.spec.ts
Adds `setFocus` methods to Textarea and Select
ASTRO-5772
https://github.com/RocketCommunicationsInc/astro/pull/1086
=> more focus meowthds

.changeset/serious-pans-sell.md, packages/web-components/src/components/rux-button/rux-button.tsx, packages/web-components/src/components/rux-button/test/button.spec.ts
reverts button reflection feature temporarily to make 7.9.1 easier to release
=> revert button reflection temporarily

packages/web-components/src/components/rux-timeline/helpers.ts, packages/web-components/src/components/rux-timeline/test/timeline.spec.ts
Adds a fix for a 'date-fns-tz' issue that's listed here: https://github.com/date-fns/date-fns/issues/571
Test written for fix. 
[ASTRO-5872](https://rocketcom.atlassian.net/browse/ASTRO-5872)
https://github.com/RocketCommunicationsInc/astro/issues/1101
Timeline's date labels would repeat if they crossed a DST change.
=> test(timeline): dst bug

packages/starter-kits/html-js-starter/index.html
unpkg scripts were broken in the JS starter kit. 
https://github.com/RocketCommunicationsInc/astro/issues/1108
=> chore(starter-kits): update js starter kit to use jsdelivr

packages/web-components/src/stories/astro-uxds/welcome/react.stories.mdx
Our React docs had an incorrect example in the testing section. Also, the link to the test app repo at the bottom of the React docs page in now incorrect since that test repo has been removed in recent versions. The link now points to 7.7, which has the test repo. 
https://github.com/RocketCommunicationsInc/astro/issues/1114
We'll need to do a SB publish for this to go live. 
User noticed syntax error in code examples. 
Test app repo couldn't be easily found.
=> docs(react): fix/update docs

.changeset/green-rules-knock.md, packages/react/package-lock.json, packages/web-components/src/stories/astro-uxds/welcome/vue.stories.mdx, packages/web-components/stencil.config.ts
Adds the `experimentalImportInjection` flag to `stencil.config`. This allows for our components to work in other bundlers like Vite. 
The flag above has been deprecated in Stencil 3.2, and was just renamed to ` enableImportInjection` so we'll need to update that when we upgrade Stencil.
https://rocketcom.atlassian.net/browse/ASTRO-6072
https://github.com/RocketCommunicationsInc/astro/issues/1097
https://github.com/RocketCommunicationsInc/astro/discussions/1112
This increases our overall bundle size, but allows for our components (specifically our React wrapper) to work in Vite and other bundler environments like it. 
Vite support 
Increases bundle size.
=> feat: import injection 

.changeset/mighty-countries-know.md, packages/web-components/src/components/rux-clock/rux-clock.scss, packages/web-components/src/components/rux-monitoring-progress-icon/rux-monitoring-progress-icon.scss
adds tabular nums for clock, monitoring progress icon so they don't jitter when using system fonts
=> fix(clock, monitoring-progress-icon): add tabular nums

.changeset/good-toes-think.md, packages/web-components/src/components/rux-card/rux-card.tsx
Added a new part: container to run-card. This part is on the div with class 'rux-card'
[ASTRO-5893](https://rocketcom.atlassian.net/browse/ASTRO-5893)
developers were previously unable to remove the box-shadow from card because it was placed on an element without a part. Now they can remove the box shadow if they wish.
=> feat(card) add part: container to the outer container

.changeset/nine-fishes-carry.md, packages/web-components/src/components/rux-select/rux-select.tsx, packages/web-components/src/components/rux-select/test/select.spec.ts, packages/web-components/src/index.html
When dynamically adding/removing `rux-option`'s from a `rux-option-group`, the value of the `rux-select` would not properly sync to a `rux-option` within the `rux-option` group. 
The method to sync these values wasn't being called when a `rux-option-group` emitted it's changed event.
I left the `src/index` with an example of the fix in action for convenience  of review. Check out the astro-stencil preview to see it. 
Here's a sandbox version of the bug without the fix as well: https://codesandbox.io/s/misty-moon-0c2nfm?file=/index.html
https://rocketcom.atlassian.net/browse/ASTRO-6186
https://github.com/RocketCommunicationsInc/astro/issues/1125
Added 2 tests for adding/removing `rux-option`'s from a `rux-option-group` and having the pre-selected value persist. 
Allows for pre-selected …
=> fix(select): Options within an opt group now sync to select value when slot changes

packages/web-components/package-lock.json, packages/web-components/package.json
moves stencil/postcss to dev dependency
=> chore: move stencil/postcss to devdep

.changeset/silver-ducks-rhyme.md, packages/web-components/src/components/rux-input/rux-input.tsx, packages/web-components/src/components/rux-input/test/index.html, packages/web-components/src/components/rux-input/test/input.spec.ts
When you programatically change run-ionput's type from 'password' to anything else, the show/hide password toggle would remain on the input.
This PR fixes that.
[ASTRO-6230](https://rocketcom.atlassian.net/browse/ASTRO-6230)
Probably a small use case, but it will make it work properly on our playground.
=> fix(rux-input) password show/hide button

packages/web-components/src/components/rux-progress/rux-progress.tsx, packages/web-components/src/components/rux-progress/test/progress.spec.ts
Changes progress to respect max instead of changing max to equal value when value gets beyond max. 
This seems to be legacy functionality and isn't justified anymore. Was brought up in the demo day and was declared a bug. 
This fix swaps the (backwards) functionality of max changing to equal value with value instead changing to equal max if value is being incremented past the max prop. 
Updates a test.
https://rocketcom.atlassian.net/browse/ASTRO-6244
Noticed by user. Makes progress act as you would expect
=> fix(progress): respect max when value increases

.changeset/kind-crabs-grow.md, packages/web-components/src/components/rux-log/rux-log.tsx, packages/web-components/src/components/rux-log/test/index.html
Added a watch decorator to filter and had search update when filter changed and the two fall out of sync.
[ASTRO-1842](https://rocketcom.atlassian.net/browse/ASTRO-1842)
Pretty easy fix though I am wondering if I should add an event for the filter change...
Low impact issue but in the case that a dev is trying to filter from external js, the filter string didn't populate into the search input (though the items did still filter properly). This makes sure that the filter and the search stay in sync.
=> fix(rux-log) search input updates when filter is updated programatically 

.changeset/popular-ties-sleep.md, packages/web-components/src/components/rux-textarea/rux-textarea.scss, packages/web-components/src/index.html
~Testing moving height to host.~
Adjusted this fix to set height on textarea to min-height so that rows="X" will work again.
[ASTRO-5903](https://rocketcom.atlassian.net/browse/ASTRO-5903)
Width can be set on rux-textarea but height can't.
Decided to fix this by fixing the rows prop. it wasn't properly working because height was set on textarea instead of min-height.
So the problem with setting height this way is that there is more than one element in rux-textarea to contend with. Label sits on top and help/error sits on bottom. It's not a problem if you don't want the textarea to be resizable but if you DO then the height doesn't act as you would expect. setting min-height would.. but is that the less confusing option?
Carbon uses rows to set height. if you set height to their web …
=> fix(textarea) move height to :host

.changeset/heavy-horses-jump.md, packages/web-components/src/components/rux-accordion/rux-accordion-item/rux-accordion-item.tsx
added part=content to the span that wraps the details slot. It has some padding on it and that can't be manipulated without the part.
[Astro-6233](https://rocketcom.atlassian.net/browse/ASTRO-6233)
Allows people to remove padding from the content slot wrapper if they need to.
=> feat(rux-accordion-item) add part to the content wrapper

packages/web-components/src/stories/popup.stories.mdx
Noticed that the `placement` prop wasn't hooked up in storybook so I made a quick fix. I thought the problem was the same as tooltip but it appears not to be the case.
No ticket, noticed this on accident when checking out a different PR.
=> docs(popup) storybook fix

packages/web-components/tests/utils/_astro-fixtures.ts
adds a lil optional `testName` option to our test config that you can pass in like: 
```
test.use({ component: 'rux-select', testName: 'inline' })
```
so now we can break up our chonky VRT tests into smaller directories. right now, everything is under "basic" but I wanted to create a new directory for inline select
=> test: add testName option

.changeset/mean-melons-float.md, packages/web-components/src/components.d.ts, packages/web-components/src/components/rux-textarea/rux-textarea.tsx
Added readonly attribute to rux-textarea in a way that mimics rux-input
[ASTRO-6600](https://rocketcom.atlassian.net/browse/ASTRO-6600)
I've run into some dev instances in the TTC/GRM apps where it would have been nice to have readonly available.
=> feat(rux-textarea) add readonly attribute

packages/web-components/src/stories/tooltip.stories.mdx
Removes the tooltip placement 'center' variants from SB. This includes 
- top center
- bottom center
- right center
- left center 
These placements don't exist anymore. Instead they are just 'top', 'bottom', ect. 
https://rocketcom.atlassian.net/browse/ASTRO-6725
=> docs(tooltip): removed center variants

.changeset/metal-plants-sell.md, packages/web-components/src/components/rux-tabs/rux-tabs.tsx
Fixed an error in rux-tabs where if a tab was not clicked then it would throw an error.
[ASTRO-6762](https://rocketcom.atlassian.net/browse/ASTRO-6762)
Its not a huge thing, just prevents the tabs from throwing errors in testing.
=> Km.6762 rux tabs onclick fix

.changeset/quiet-readers-flow.md, packages/web-components/src/components/rux-global-status-bar/rux-global-status-bar.scss
I moved some of the padding from `host` to the inner `<header>` container so that when a menu or other focusable item appears in the left or right slot, the focus state won't get cut off by the `overflow:hidden` on `<header>` moving overflow:hidden to host wasn't an option because it would then hide any slotted menus.
[ASTRO-6766](https://rocketcom.atlassian.net/browse/ASTRO-6766)
I ran VRTs and it looks like my change doesn't affect the layout in any way. :)
The GSB will cut off focus state of anything slotted in the right-slot or left-slot. The right slot is FOR menus which should always have a focus state.. so it doesn't make sense to have the developer need to tweak this every time in order to get the focus display right.
=> fix(gsb) adjust paddings so that focus states on the left/right can be visible

.changeset/few-badgers-itch.md, packages/web-components/src/components/rux-tabs/rux-tabs.tsx, packages/web-components/src/components/rux-tabs/test/tabs.spec.ts
Rux-tabs have been pretty well inextricably linked to rux-tab-panels. So much so that in order to run _addTabs() after the initial connection, rux-tabs needs to hear a 'ruxregisterpanels' event. This is fine, unless you're not using panels. For example, in React it sometimes makes sense to pull in tabs to change certain states but not explicitly set panels.
[example](https://grm-equipment-react-ts.netlify.app)
This PR runs _addTabs on rux-tabs slots change since all addTabs does is look through rux-tabs and put every rux-tab found into an array so that keyboard commands can be run on them.
Secondarily, I've added a function that sets the first tab item to tabindex=0 when no tab is set to 'selected'. this way you can tab back into rux-tabs even when there is no explicitly set rux-tab. …
=> fix(rux-tabs) fix some keyboard functionality

.changeset/five-ladybugs-smell.md, packages/web-components/src/components/rux-push-button/rux-push-button.tsx
Removes the default label text 'Push Button'
ASTRO-3925
We also probably want to deprecate and remove the `label` prop altogether in favor of slots in the future.
=> fix(push-button): remove default label

.changeset/gentle-games-brush.md, packages/web-components/package-lock.json, packages/web-components/src/components.d.ts, packages/web-components/src/components/rux-dialog/readme.md, packages/web-components/src/components/rux-dialog/rux-dialog.tsx, packages/web-components/src/components/rux-dialog/test/dialog.spec.ts
This adds a public `toggleOpen` method to rux-dialog that makes the dialog easier to open and close. 
https://rocketcom.atlassian.net/browse/ASTRO-6841
On FDS we were having a problem where the open prop on dialog would get out of sync, and you had to listen to the closed and opened events in order to toggle the open prop correctly, which can be cumbersome and unintuitive.
=> feat(dialog): toggleOpen, openDialog, closeDialog methods

.changeset/beige-bats-kiss.md, packages/web-components/src/components/rux-timeline/rux-timeline.tsx
Fixes a bug where the playhead on timeline wouldn't update accordingly when interval was changed. 
https://rocketcom.atlassian.net/browse/ASTRO-6872
https://github.com/RocketCommunicationsInc/astro/issues/1238
=> Mj.timeline playhead interval change

.changeset/neat-tips-hear.md
Adds a changest for the timeline playhead indicator prop.
=> docs: add missing timeline changeset

.changeset/funny-hotels-hear.md, packages/web-components/src/components/rux-timeline/helpers.ts, packages/web-components/src/components/rux-timeline/test/timeline.spec.ts
Fixes an issue where a range spanning over Nov 5th would cause issues on how the timeline displayed. 
https://github.com/RocketCommunicationsInc/astro/issues/1258
https://github.com/RocketCommunicationsInc/astro/issues/1101
Solution was pulled from https://github.com/date-fns/date-fns/blob/main/src/differenceInDays/index.ts#L17C2-L17C2
=> fix(timeline): fixed issue with Nov DST

.changeset/rich-cherries-hunt.md, packages/web-components/src/components/rux-tooltip/rux-tooltip.tsx, packages/web-components/src/components/rux-tooltip/test/tooltip.spec.ts
Added an escape key listener that will close a tooltip if the tooltip trigger is either hovered or focused. If it is neither the escape key won't act on it.
[ASTRO-6882](https://rocketcom.atlassian.net/browse/ASTRO-6882)
Cory (from Shoelace) mentioned that tooltips should have ability to close without moving the mouse or unfocusing. Seemed like a good idea.
Make sure this is the functionality we want. I could remove the if statements in the listener and have all tooltips close whenever escape is pressed. That would also be valid. This is just more specific.
=> Km.6882 add keyboard control tooltip

.changeset/calm-mugs-fly.md, packages/web-components/src/components/rux-pop-up/rux-pop-up.tsx
This fixes an attribute error in the console log if popup doesn't have a trigger.
[6883](https://rocketcom.atlassian.net/jira/software/c/projects/ASTRO/issues/ASTRO-6883)
I saw an instance in a recent project where the popup was being used without a trigger and one of the functions was causing it to throw an error. I fixed that function.
There are other errors that are thrown if you try to use popup without a slotted trigger.. but those would take more logic to solve.. might be worth future consideration though as technically you can programmatically show/hide a popup so it doesn't need a trigger for anything other than autopositioning.
I didn't work up a fix for that right now because it would likely be a major change.
=> Astro-6883 Fix reference error

packages/web-components/src/components/rux-timeline/rux-timeline.tsx
Timeline was throwing a playhead range error even when setting the playhead to `undefined`. 
This adds a check before throwing the error to ensure that the playhead is assigned an actual date that could be incorrect. 
https://github.com/RocketCommunicationsInc/astro/issues/1284
Removes a console error that shouldn't be thrown.
=> fix(timeline): playhead no longer throws error when undefined

.changeset/five-snails-call.md, packages/web-components/src/components/rux-select/rux-select.tsx, packages/web-components/src/components/rux-select/test/select.spec.ts
Fixes an issue where a multi-select could have a string value instead of an array value if only one option was present. 
Customer email. 
Makes select menu act as our docs state: If multiple is true, value is an array.
=> fix(select): value is always an array when multiple is true

.changeset/swift-pans-chew.md, packages/web-components/src/components/rux-card/readme.md, packages/web-components/src/components/rux-card/rux-card.tsx
Card was missing it's footer slot documentation on Storybook. 
https://rocketcom.atlassian.net/jira/software/projects/DIW/boards/95
Better, more accurate docs.
=> docs(card): add missing footer slot to docs

.changeset/slow-schools-grow.md, packages/web-components/src/components/rux-button/rux-button.scss
Fixes an issue where clicking and dragging an icon-only, borderless button would show the background. 
https://rocketcom.atlassian.net/browse/DIW-138
https://github.com/RocketCommunicationsInc/astro/issues/1320
Fixes style bug.
=> fix(button): icon-only borderless bug

packages/web-components/README.md, packages/web-components/src/stories/astro-uxds/StartHere.mdx
The `unpkg` tool is no longer working as expected so we are replacing it with `jsdelivr`
https://rocketcom.atlassian.net/browse/AP-400?linkSource=email
I created an "astro-playground" on my personal git hub. For some reason I could not push to a new repository created under the Rocket account.
https://github.com/brothhammer/astro-playground
If you pull that repo you can run with the "Liver Server" plugin for VS code by right clicking in the file and selecting run with Live Server.
After we merge this we need to properly deploy StoryBook. The instructions for that can be found in Confluence here
https://rocketcom.atlassian.net/wiki/spaces/AS11/pages/3740565534/Astro+Deployment+Instructions
We do not want customers getting frustrated trying to follow the Quick Start instructions.
=> replace unpkg with jsdeliver in quick start instructions

.changeset/tough-months-drop.md, .github/workflows/pull-request.yml, packages/web-components/src/components/rux-segmented-button/readme.md, packages/web-components/src/components/rux-segmented-button/rux-segmented-button.tsx
This PR adds CSS shadow parts to the `<ul>` and `<li>` elements of `<rux-segmented-button>`. 
This was added due to it being difficult to have the `<rux-segmented-button>` fill it's parents width, as you couldn't set the width on the `<ul>` or `<li>` elements in the shadow-dom.
NOTE: this PR updates the ubuntu version used by github actions to 22.04. 20.04 was deprecated, and 24.04 doesn't work with playwright's dependencies yet. 
Raised by @dgwiltjer when he was trying to make segmented-button fit the width of its parent container. There is a work around, but it involves semi-complex CSS using container queries - adding parts makes this easier and covers more use cases. 
Allows for more control over the size of the button portions of segmented button.
=> Add `ul` and `li` parts to segmented-button

packages/web-components/src/stories/popup.mdx, packages/web-components/src/stories/popup.stories.js
The default pop up story is not being rendered on the AstorUXDS site.
(https://rocketcom.atlassian.net/jira/software/projects/AP/boards/119?assignee=712020%3A6a79a1e3-7381-4656-9516-c09792ad18be%2C60e2c268bd7f5d006886d1bf&selectedIssue=AP-489)
This could also be fixed in the AstroUXDS repo by removing the -story suffix. I think it is better to update here to keep the expected -story suffix. Looking at the breadcrumb story set up which works you would expect the Pop Up to work as well. **Files of interest for comparison `breadcrumb.mdx` and `breadcrumb.stories.js`**
- The -story suffix is added by Storybook for MDX Canvas references.
- If the CSF export is named `DefaultStory`, the ID matches what MDX expects.
- If the CSF export is named `Default`, Storybook is inconsistent in its mapping …
=> include -story suffix

.changeset/nervous-beers-buy.md, packages/web-components/src/components.d.ts, packages/web-components/src/components/rux-global-status-bar/readme.md, packages/web-components/src/components/rux-global-status-bar/rux-global-status-bar.scss, packages/web-components/src/components/rux-global-status-bar/rux-global-status-bar.tsx, packages/web-components/src/stories/global-status-bar.mdx, packages/web-components/src/stories/global-status-bar.stories.js
This PR adds a new `compact` prop to GSB. This renders the GSB in a shorter, more slim version as per the community design [here](https://www.figma.com/design/nk7kX4nDtpfIFlP6DnKNXY/Slim-GSB?node-id=0-1&p=f&t=FXV57zmxkGJKz3QB-0).
Adds compact story as well.
Update our component to match new designs.
=> feat: Add compact variant to GSB
