README.md, packages/react/README.md
Updates the react readme with current info, adds brief astro description and package list to root readme. 
Just an initial update in case someone happens to look at this repo. We'll definitely want to update the root readme further at some point.
na
Adds further documentation.
=> docs: inital readme updates

packages/web-components/src/components/rux-monitoring-icon/rux-monitoring-icon.scss
Updates monitoring icon to be in line with Figma. 
Figma design: https://www.figma.com/file/ZtHeSWpISd8hJjN46uY9pm/Astro-UX-Design-System?node-id=5503%3A131798
https://rocketcom.atlassian.net/browse/ASTRO-2046
This will be a faster review once the netlify deploy previews are up and running again. 
Updates to match figma design.
=> Astro 2046 monitoring icon update

packages/starter-kits/react-starter/package.json, packages/starter-kits/svelte-starter/package.json, packages/web-components/src/stories/astro-sandboxes/forms/html/index.html, packages/web-components/src/stories/astro-sandboxes/forms/react/basic/package.json, packages/web-components/src/stories/astro-sandboxes/forms/react/basic/src/App.js, packages/web-components/src/stories/astro-sandboxes/forms/react/validation/package.json, packages/web-components/src/stories/astro-sandboxes/forms/react/validation/src/App.js, packages/web-components/src/stories/astro-sandboxes/forms/svelte/basic/Form.svelte, packages/web-components/src/stories/astro-sandboxes/forms/svelte/basic/package.json, packages/web-components/src/stories/astro-sandboxes/forms/svelte/validation/Form.svelte, packages/web-components/src/stories/astro-sandboxes/forms/svelte/validation/package.json, packages/web-components/src/stories/astro-sandboxes/forms/vue/basic/package.json, packages/web-components/src/stories/astro-sandboxes/forms/vue/basic/src/App.vue, packages/web-components/src/stories/astro-sandboxes/forms/vue/validation/package.json, packages/web-components/src/stories/astro-sandboxes/forms/vue/validation/src/App.vue, packages/web-components/src/stories/astro-sandboxes/sign-in/index.html
Bumps the versions in all sandbox examples and starter-kits. Updates codesandbox examples event names.
https://rocketcom.atlassian.net/browse/ASTRO-2208
Updates starter kits and codesandbox's to use current version.
Updates event names in codesandbox's.
Updates all occurrences of option -> rux-option in sandboxes (or RuxOption for react)
=> Bump sandbox versions

packages/starter-kits/html-js-starter/index.html, packages/starter-kits/html-js-starter/package.json, packages/starter-kits/html-js-starter/sandbox.config.json
Creates the HTML/JS starter kit.
https://rocketcom.atlassian.net/browse/ASTRO-2215
adds static html/js starter kit. After this is merged, the path can be imported into codesandbox and linked in SB.
=> feat(starter-kits): created html starter kit

packages/web-components/src/stories/astro-sandboxes/forms/angular/basic-form/package-lock.json, packages/web-components/src/stories/astro-sandboxes/forms/angular/basic-form/package.json, packages/web-components/src/stories/patterns/forms/form-angular.stories.mdx
adds the angular form codesandbox link to storybook
[ASTRO-2048](https://rocketcom.atlassian.net/browse/ASTRO-2048)
* styles arent appearing because astro web components isnt showing up in codesandbox. I declared it as a dependency in this PR so once it gets merged, the styles should appear.
* will need to remember to switch the version of astrouxds/angular to stable
=> Astro 2048 angular form stories

packages/web-components/src/components/rux-tree-node/rux-tree-node.spec.tsx, packages/web-components/src/components/rux-tree/rux-tree.tsx, packages/web-components/src/stories/checkbox.stories.mdx, packages/web-components/src/stories/input.stories.mdx, packages/web-components/src/stories/menu-item.stories.mdx, packages/web-components/src/stories/modal.stories.mdx, packages/web-components/src/stories/popup.stories.mdx, packages/web-components/src/stories/push-button.stories.mdx, packages/web-components/src/stories/radio-group.stories.mdx, packages/web-components/src/stories/radio.stories.mdx, packages/web-components/src/stories/segmented-button.stories.mdx, packages/web-components/src/stories/select.stories.mdx, packages/web-components/src/stories/slider.stories.mdx, packages/web-components/src/stories/switch.stories.mdx, packages/web-components/src/stories/tabs.stories.mdx, packages/web-components/src/stories/textarea.stories.mdx, packages/web-components/src/stories/tree-node.stories.mdx, packages/web-components/src/stories/tree.stories.mdx
fixes tree node not deselecting previous nodes because the event name wasn't updated.
also updated all of the storybook actions to use the new event names
[ASTRO-2210](https://rocketcom.atlassian.net/browse/ASTRO-2210)
=> Astro 2210 fix tree node

.github/workflows/pull-request.yml, packages/react/package-lock.json, packages/react/package.json
Adds React wrapper tests to github workflows.
The action symlinks /web-components and /react in order to run tests on any changes made to web-components. 
https://rocketcom.atlassian.net/browse/ASTRO-2361
Allows us to see React test results on every PR to ensure the wrapper is working.
There may be some places where a lerna command could replace some of the repeating npm commands.
=> Astro 2361 react tests

packages/astro-uxds/.gitignore, packages/astro-uxds/package-lock.json, packages/astro-uxds/package.json
adds npm command to pull images from figma
[ASTRO-2404](https://rocketcom.atlassian.net/browse/ASTRO-2404)
waiting on package update
=> feat(astro-uxds): import image assets from figma

packages/ag-grid-theme/src/styles/astro-ag-theme.css, packages/ag-grid-theme/src/styles/scss/astro-theme.scss, packages/web-components/src/common/functional-components/FormFieldMessage/form-field-message.scss, packages/web-components/src/components/rux-button/rux-button.scss, packages/web-components/src/components/rux-checkbox/rux-checkbox.scss, packages/web-components/src/components/rux-classification-marking/rux-classification-marking.scss, packages/web-components/src/components/rux-clock/rux-clock.scss, packages/web-components/src/components/rux-global-status-bar/rux-global-status-bar.scss, packages/web-components/src/components/rux-input/rux-input.scss, packages/web-components/src/components/rux-menu-item/rux-menu-item.scss, packages/web-components/src/components/rux-modal/rux-modal.scss, packages/web-components/src/components/rux-monitoring-icon/rux-monitoring-icon.scss, packages/web-components/src/components/rux-monitoring-progress-icon/rux-monitoring-progress-icon.scss, packages/web-components/src/components/rux-notification/rux-notification.scss, packages/web-components/src/components/rux-push-button/rux-push-button.scss, packages/web-components/src/components/rux-radio/rux-radio.scss, packages/web-components/src/components/rux-segmented-button/rux-segmented-button.scss, packages/web-components/src/components/rux-select/rux-select.scss, packages/web-components/src/components/rux-table/rux-table-header-cell/rux-table-header-cell.scss, packages/web-components/src/components/rux-tabs/rux-tabs.scss, packages/web-components/src/components/rux-textarea/rux-textarea.scss, packages/web-components/src/components/rux-tree-node/rux-tree-node.scss, packages/web-components/src/components/rux-tree/rux-tree.scss, packages/web-components/src/global/_reset.scss, packages/web-components/src/global/tokens/_colors-dark.scss, packages/web-components/src/global/tokens/_colors-global.css, packages/web-components/src/global/tokens/_colors-light.css, packages/web-components/src/global/tokens/_tokens.scss
just importing the new tokens from figma. we had to change our typography tokens slightly so the names needed to be updated from font-m1-font-size -> font-monospace-1-font-size. a recent update in the plugin also removed the ability to do aliasing, but that doesn't really affect anything.
=> Token update

packages/astro-uxds/package-lock.json, packages/astro-uxds/package.json
bumps figma export package so it no longer saves a meta file
=> chore(astro-uxds): bump figma export version

packages/web-components/src/components/rux-input/rux-input.scss, packages/web-components/src/components/rux-textarea/rux-textarea.scss, packages/web-components/src/global/tokens/_colors-dark.scss, packages/web-components/src/global/tokens/_colors-global.css, packages/web-components/src/global/tokens/_colors-light.css, packages/web-components/src/global/tokens/_tokens.scss
adds new placeholder-text design token and updates input and textarea to use it.
[ASTRO-2459](https://rocketcom.atlassian.net/browse/ASTRO-2459)
=> feat(web-components): add placeholder text design token

packages/web-components/src/components/rux-button/rux-button.scss, packages/web-components/src/components/rux-checkbox-group/rux-checkbox-group.scss, packages/web-components/src/components/rux-checkbox/rux-checkbox.scss, packages/web-components/src/components/rux-classification-marking/rux-classification-marking.scss, packages/web-components/src/components/rux-global-status-bar/rux-global-status-bar.scss, packages/web-components/src/components/rux-input/rux-input.scss, packages/web-components/src/components/rux-monitoring-progress-icon/rux-monitoring-progress-icon.scss, packages/web-components/src/components/rux-pop-up-menu/rux-pop-up-menu.scss, packages/web-components/src/components/rux-progress/rux-progress.scss, packages/web-components/src/components/rux-push-button/rux-push-button.scss, packages/web-components/src/components/rux-radio-group/rux-radio-group.scss, packages/web-components/src/components/rux-radio/rux-radio.scss, packages/web-components/src/components/rux-segmented-button/rux-segmented-button.scss, packages/web-components/src/components/rux-select/rux-select.scss, packages/web-components/src/components/rux-switch/rux-switch.scss, packages/web-components/src/components/rux-textarea/rux-textarea.scss, packages/web-components/src/global/_variables.scss, packages/web-components/src/global/tokens/_colors-dark.scss, packages/web-components/src/global/tokens/_colors-global.css, packages/web-components/src/global/tokens/_colors-light.css, packages/web-components/src/global/tokens/_tokens.scss, packages/web-components/src/stories/astro-uxds/welcome/StartHere.stories.mdx
updates components to use border radii tokens from figma
[ASTRO-2462](https://rocketcom.atlassian.net/browse/ASTRO-2462)
VRT false positives - progress radius was incorrect on dev. checkbox had no readius
=> Astro 2462 radii tokens

.gitignore, packages/ag-grid-theme/dist/main.css, packages/angular/src/directives/proxies.ts, packages/web-components/src/components/rux-notification/readme.md, packages/web-components/src/components/rux-select/readme.md
=> chore: run build

packages/web-components/src/common/commonTypes.module.ts, packages/web-components/src/components/rux-classification-marking/readme.md, packages/web-components/src/components/rux-classification-marking/rux-classification-marking.scss, packages/web-components/src/components/rux-classification-marking/rux-classification-marking.tsx, packages/web-components/src/components/rux-classification-marking/test/rux-classification-marking.spec.tsx, packages/web-components/src/stories/classification-marking.stories.mdx
adds cui/controlled classification marking options
[ASTRO-1463](https://rocketcom.atlassian.net/browse/ASTRO-1463)
=> Astro 1463 controlled classification

packages/web-components/package-lock.json, packages/web-components/package.json
fixes issue where duplicate names were not showing in storybook. 
fixed in https://github.com/RocketCommunicationsInc/storybook-addon-docs-stencil/pull/2
[ASTRO-2511](https://rocketcom.atlassian.net/browse/ASTRO-2511)
=> build(web-components): bump docs addon

lerna.json, packages/ag-grid-theme/package-lock.json, packages/ag-grid-theme/package.json, packages/angular/package-lock.json, packages/angular/package.json, packages/astro-uxds/package-lock.json, packages/astro-uxds/package.json, packages/react/package-lock.json, packages/react/package.json, packages/web-components/package-lock.json, packages/web-components/package.json
=> Release 6.0.5

packages/web-components/package-lock.json, packages/web-components/package.json
=> Fix revert sb docs plugin

packages/astro-uxds/_content/patterns/data-visualization.md
Fixed misspelling of gauge and did some quick capitalization fixes for some app section titles
None
Quick typo fixes
=> docs(astro/uxds): fix data viz typos

packages/web-components/package-lock.json, packages/web-components/package.json, packages/web-components/src/stories/checkbox-group.stories.mdx
fixes issue caused by storybook docs update 1.0.9. 
also removes the 'name' arg on checkbox since its not real
=> Fix sb docs

packages/web-components/src/stories/astro-uxds/welcome/javascript.stories.mdx
=> docs(web-components): fix typo

packages/starter-kits/angular-starter/package-lock.json, packages/starter-kits/angular-starter/package.json, packages/starter-kits/react-starter/package-lock.json, packages/starter-kits/react-starter/package.json
=> chore(starter-kits): bump versions

.github/workflows/pull-request.yml, packages/angular/src/directives/proxies.ts, packages/astro-uxds/_content/patterns/data-visualization.md, packages/react/__tests__/RuxModal.spec.tsx, packages/web-components/.storybook/preview-head.html, packages/web-components/CHANGELOG.md, packages/web-components/package-lock.json, packages/web-components/package.json, packages/web-components/src/components.d.ts, packages/web-components/src/components/rux-button-group/readme.md, packages/web-components/src/components/rux-button/readme.md, packages/web-components/src/components/rux-button/rux-button.tsx, packages/web-components/src/components/rux-modal/readme.md, packages/web-components/src/components/rux-modal/rux-modal.scss, packages/web-components/src/components/rux-modal/rux-modal.tsx, packages/web-components/src/components/rux-modal/test/index.html, packages/web-components/src/components/rux-modal/test/rux-modal.e2e.js, packages/web-components/src/components/rux-modal/test/rux-modal.spec.tsx, packages/web-components/src/index.html, packages/web-components/src/stories/astro-uxds/welcome/javascript.stories.mdx, packages/web-components/src/stories/checkbox-group.stories.mdx, packages/web-components/src/stories/modal.stories.mdx
=> Clean slots branch

.github/CODEOWNERS.md
Adds myself, Mark and Duncan as codeowners so we can have a required review from one of us for PR merges.
After this, @markacianfrani you'll have to add the branch protection 
https://rocketcom.atlassian.net/browse/ASTRO-2719
=> chore(astro): added codeowners.md

.changeset/early-beans-shake.md, .changeset/mighty-years-jump.md, .changeset/pre.json, .changeset/rude-chicken-mate.md
adds changesets for the modal work currently in next
=> Setup next changesets

.github/workflows/release.yml
=> build: bump node

.changeset/pretty-fans-fail.md, packages/web-components/src/components/rux-button-group/readme.md, packages/web-components/src/components/rux-button-group/rux-button-group.tsx, packages/web-components/src/components/rux-button-group/test/rux-button-group.spec.tsx
https://rocketcom.atlassian.net/browse/ASTRO-2633
Part of the shadow part effort
=> Astro 2633 button group parts

.changeset/purple-lemons-lie.md, packages/web-components/src/components/rux-button-group/test/__snapshots__/rux-button-group.spec.tsx.snap, packages/web-components/src/components/rux-button/readme.md, packages/web-components/src/components/rux-button/rux-button.tsx, packages/web-components/src/components/rux-button/test/__snapshots__/rux-button.spec.tsx.snap
Adds a container shadow part to rux-button
https://rocketcom.atlassian.net/browse/ASTRO-2634
adds shadow part for rux-button
=> feat: astro 2634 button parts

packages/astro-uxds/_includes/_footer.njk
Update references of SMC to SSC in footer
[ASTRO-2762](https://rocketcom.atlassian.net/jira/software/c/projects/ASTRO/issues/ASTRO-2762)
Org name change needs to be updated
=> docs(astro-uxds): update references of SMC to SSC in footer

packages/astro-uxds/_content/components/clock.md
Updates the docs on astrouxds for recent clock changes regarding Julian date.
https://rocketcom.atlassian.net/browse/ASTRO-2871
Last part of this ticket. Should have included it in the other PR, sorry @markacianfrani 
Docs are now up to date as for compliance and rux-clock.
=> docs(astro-uxds): Updated clock.md in astrouxds

packages/astro-uxds/_content/components/progress.md
Fixed three typos in the Appearance & Behavior Section. seeconds > seconds. takees > takes. th > the.
=> docs(astro/uxds): fix progress typos

packages/astro-uxds/_content/components/clock.md
Updated comma usage to be consistent with other page documentation and fixed Example image alt text.
https://rocketcom.atlassian.net/browse/ASTRO-2830
=> docs(astro-uxds): quick typo fixes

packages/astro-uxds/_content/index.md
=> fix(astro-uxds): change airmen to guardian

.github/PULL_REQUEST_TEMPLATE.md
adds regressions and evergreen browsers to the pr template checklist
=> docs: pr temp update

packages/astro-uxds/_content/index.md
=> docs(astro-uxds): update homepage copy

packages/angular/src/directives/proxies.ts, packages/web-components/src/components/rux-button/readme.md, packages/web-components/src/components/rux-input/readme.md, packages/web-components/src/components/rux-input/rux-input.tsx, packages/web-components/src/components/rux-log/readme.md, packages/web-components/src/stories/input.stories.mdx
Adds some documentation that I forgot with the rux-input suffix, prefix and focus event change. 
- Parts documented
- Focus event added to SB
- Stencil build
https://rocketcom.atlassian.net/browse/ASTRO-3213
Everything now documented
=> docs(input): documented new parts, added focus event to SB

packages/web-components/src/stories/themes/tailwind.stories.mdx
Adds link to the Tailwind theme
ASTRO-3159
=> docs: added tailwind theme page

packages/angular/src/directives/proxies.ts, packages/react/__tests__/RuxNotification.spec.tsx, packages/web-components/src/components/rux-input/readme.md, packages/web-components/src/components/rux-option/readme.md
the recent notification changes broke the notification test in react, this fixes that
=> test(react): fixed notification test, stencil build

packages/web-components/src/stories/button-group.stories.mdx
fixes h-align prop in storybook for button group
=> docs: fix button group story

.changeset/cuddly-snails-clap.md, .changeset/grumpy-beans-press.md, .changeset/kind-rabbits-press.md, .changeset/red-ties-teach.md, .changeset/shiny-yaks-hide.md, .changeset/six-carpets-rush.md, .changeset/sixty-avocados-yawn.md, .changeset/slimy-waves-design.md, .changeset/tall-pears-lay.md, packages/angular/CHANGELOG.md, packages/angular/package-lock.json, packages/angular/package.json, packages/astro-uxds/CHANGELOG.md, packages/astro-uxds/_content/releases.md, packages/astro-uxds/package-lock.json, packages/astro-uxds/package.json, packages/react/CHANGELOG.md, packages/react/package-lock.json, packages/react/package.json, packages/web-components/CHANGELOG.md, packages/web-components/package.json
=> Release 6.5.0

packages/react/package-lock.json, packages/web-components/.storybook/main.js, packages/web-components/.storybook/manager.js, packages/web-components/package-lock.json, packages/web-components/package.json
Adds the https://www.npmjs.com/package/@storybook/addon-google-analytics to our web-components. 
analytics bb
=> feat: storybook google analytics addon

.changeset/chilly-taxis-approve.md, .changeset/happy-foxes-bathe.md, .changeset/loud-humans-study.md, .changeset/orange-onions-serve.md, packages/angular/CHANGELOG.md, packages/angular/package.json, packages/astro-uxds/CHANGELOG.md, packages/astro-uxds/_content/releases.md, packages/astro-uxds/package.json, packages/react/CHANGELOG.md, packages/react/package.json, packages/web-components/CHANGELOG.md, packages/web-components/package.json
=> Release 6.6.0

packages/astro-uxds/_content/releases.md
=> Fix release

packages/web-components/src/stories/select.stories.mdx
Fixes controls for select in SB, specifically the size control now works. All controls where a bit wonky so I've cleaned them up. Since this is SB specific, I didn't do a changeset. lmk if you want one tho
https://rocketcom.atlassian.net/browse/ASTRO-3334
Select SB now behaves as intended.
=> fix(select): fixed controls in SB, removed value control

.changeset/wise-drinks-compare.md, packages/angular/src/directives/proxies-list.ts, packages/angular/src/directives/proxies.ts, packages/react/src/components.tsx, packages/web-components/src/components.d.ts, packages/web-components/src/components/rux-button-group/readme.md, packages/web-components/src/components/rux-button/readme.md, packages/web-components/src/components/rux-container/readme.md, packages/web-components/src/components/rux-container/rux-container.scss, packages/web-components/src/components/rux-container/rux-container.tsx, packages/web-components/src/components/rux-container/test/__snapshots__/rux-container.spec.tsx.snap, packages/web-components/src/components/rux-container/test/index.html, packages/web-components/src/components/rux-container/test/rux-container.spec.tsx, packages/web-components/src/stories/container.stories.mdx
Implements the current design of Container
ASTRO-3297
lots of stuff here:
* No default padding on the body. 
* Too many slots. 
* Unable to reorder slots 
* No documentation
These will be addressed in a separate ticket that will change the design of the component so we can ignore them for this. This PR only aims to be a 1:1 implementation of the design in Figma. 
Other oddities:
* Table pops out of the body slot. Our table actually isn't supposed to have left/right borders either. Have a separate ticket out to address this.
* Tabs - In the tab examples, the initial content doesn't load when used in an iframe. Also separate ticket. It's an issue with the tabs component itself.
=> feat(container): add container component

LICENSE, packages/astro-uxds/LICENSE.md
updates the copyright year
ASTRO-3335
=> docs: update copyright year

.changeset/polite-peas-smell.md, .changeset/twenty-toes-sniff.md, packages/web-components/src/components/rux-tree-node/rux-tree-node.scss, packages/web-components/src/components/rux-tree/rux-tree.scss, packages/web-components/src/stories/tree-node.stories.mdx
=> style(tree): repalced wrong token, added overflow protection to tree-node

.changeset/brown-panthers-study.md, .changeset/polite-peas-smell.md, .changeset/strange-crabs-taste.md, .changeset/twenty-toes-sniff.md, .changeset/wet-buckets-smoke.md, packages/angular/CHANGELOG.md, packages/angular/package-lock.json, packages/angular/package.json, packages/astro-uxds/CHANGELOG.md, packages/astro-uxds/_content/releases.md, packages/astro-uxds/package-lock.json, packages/astro-uxds/package.json, packages/react/CHANGELOG.md, packages/react/package-lock.json, packages/react/package.json, packages/web-components/CHANGELOG.md, packages/web-components/package-lock.json, packages/web-components/package.json, packages/web-components/src/components/rux-modal/readme.md
=> Release 6.7.0

.changeset/cuddly-ears-wonder.md, .changeset/early-beans-shake.md, .changeset/mighty-years-jump.md, .changeset/pre.json, .changeset/rude-chicken-mate.md, packages/angular/CHANGELOG.md, packages/angular/package.json, packages/angular/src/directives/proxies.ts, packages/astro-uxds/CHANGELOG.md, packages/astro-uxds/package.json, packages/react/CHANGELOG.md, packages/react/package.json, packages/web-components/CHANGELOG.md, packages/web-components/package-lock.json, packages/web-components/package.json, packages/web-components/src/components.d.ts, packages/web-components/src/components/rux-button-group/readme.md, packages/web-components/src/components/rux-progress/readme.md
=> Release 7.0.0 beta.0

.changeset/soft-panthers-grow.md, packages/web-components/src/components/rux-switch/rux-switch.scss
Removed the hardcoded width 
ASTRO-3491
https://github.com/RocketCommunicationsInc/astro/issues/388
=> fix(switch): keep label within container

packages/web-components/src/components/rux-segmented-button/rux-segmented-button.scss, packages/web-components/src/components/rux-segmented-button/test/index.html
This updates the colors used by the component to match the updated design.
https://rocketcom.atlassian.net/browse/ASTRO-3388
=> style(segmented-button): update coloring

packages/angular/package-lock.json, packages/angular/package.json, packages/web-components/src/index.html
fixes the error produced by babel__traverse when running a build.
=> deps(angular): babel traverse version

packages/astro-uxds/_content/design-guidelines/grid.md
Fixed typo for Gap in Breakpoints section.
=> Fixed typo

packages/web-components/src/components.d.ts, packages/web-components/src/components/rux-button/rux-button.scss, packages/web-components/src/components/rux-button/rux-button.tsx, packages/web-components/src/components/rux-button/test/index.html
=> [Spacing] Button

packages/web-components/src/components/rux-segmented-button/rux-segmented-button.scss, packages/web-components/src/components/rux-segmented-button/rux-segmented-button.tsx, packages/web-components/src/components/rux-segmented-button/test/index.html
=> [Spacing] Segmented Button

.github/workflows/pull-request.yml, package.json, packages/react/package-lock.json, packages/web-components/package-lock.json
GA workflow overhaul: 
- Separated out tests into 3 concurrent runs; e2e, unit-tests, react
- This has brought down the testing time to ~4min 30s
- We'll now be able to better see what fails and where
GA was inconsistent and infuriating
=> build: GA workflow overhaul

.changeset/five-windows-sell.md, packages/web-components/package-lock.json, packages/web-components/package.json, packages/web-components/src/components/rux-menu-item-divider/rux-menu-item-divider.scss, packages/web-components/src/components/rux-menu-item-divider/rux-menu-item-divider.tsx, packages/web-components/src/components/rux-menu-item-divider/test/__snapshots__/rux-menu-item-divider.spec.tsx.snap, packages/web-components/src/components/rux-menu-item-divider/test/index.html
* Updates the visual design for menu item divider
* Removes the deprecated css custom prop 
ASTRO-3495
=> feat(menu-item-divider): update to match design

packages/astro-uxds/_includes/_footer.njk, packages/astro-uxds/_includes/base.template.njk
adds GA to beta.astro
ASTRO-3502
=> feat(astro-uxds): add ga to beta site

.changeset/pre.json, packages/angular-workspace/CHANGELOG.md, packages/angular-workspace/package.json, packages/angular-workspace/projects/angular/CHANGELOG.md, packages/angular-workspace/projects/angular/package.json, packages/angular-workspace/projects/angular/src/directives/proxies-list.ts, packages/astro-uxds/CHANGELOG.md, packages/astro-uxds/package.json, packages/react/CHANGELOG.md, packages/react/package.json, packages/web-components/CHANGELOG.md, packages/web-components/package.json, packages/web-components/src/components/rux-notification/readme.md, packages/web-components/stencil.config.ts
release 
NOTE: there were issues with the angularProxiesListIgnore on build. It has been temporarily commented out
=> chore: publish

packages/astro-uxds/_content/components/notification-banner.md, packages/astro-uxds/_includes/components.template.njk
* Updates the documentation for Notification banner
* Fixes the storybook previews for beta astrouxds. This won't show until this branch gets merged because it uses a special BRANCH env and for PRS its somethingsomething/pull. Will verify this works after merge
ASTRO-4013
=> docs(astro-uxds): update notification banner

packages/astro-uxds/_content/_data/navigation.json, packages/astro-uxds/_content/components/card.md
Cards docs. No images
ASTRO-4011
=> docs: card page

packages/astro-uxds/_content/components/textarea.md
textarea documentation design feedback
=> docs(textarea): textarea feedback

packages/astro-uxds/_content/components/link.md
=> docs: update link copy

packages/astro-uxds/_content/grm-service-ux-design/about-the-grm-designs.md, packages/astro-uxds/_content/grm-service-ux-design/grm-dashboard.md, packages/astro-uxds/_content/grm-service-ux-design/grm-equipment-manager.md, packages/astro-uxds/_content/grm-service-ux-design/grm-schedule.md, packages/astro-uxds/_content/service-specific-ux-design.md, packages/astro-uxds/_content/ttc-service-ux-design/about-the-ttc-designs.md, packages/astro-uxds/_content/ttc-service-ux-design/ttc-command.md, packages/astro-uxds/_content/ttc-service-ux-design/ttc-investigate.md, packages/astro-uxds/_content/ttc-service-ux-design/ttc-monitor.md
bumps mentions of Astro 5 -> Astro 7
ASTRO-4051
=> docs(astro-uxds): update mentions of astro 5

packages/astro-uxds/_content/_data/compliance.json, packages/astro-uxds/_content/components/pagination.md
Updates pagination section. 
https://rocketcom.atlassian.net/browse/ASTRO-4058
Copy updates
=> docs(astrouxds): pagination updates

packages/astro-uxds/_content/components/input-field.md, packages/web-components/package-lock.json
Updates input field copy on astrouxds. 
https://rocketcom.atlassian.net/browse/ASTRO-4041
=> Astro 4041 input update

.changeset/silver-emus-arrive.md, packages/angular/CHANGELOG.md, packages/angular/package-lock.json, packages/angular/package.json, packages/angular/src/directives/proxies.ts, packages/astro-uxds/CHANGELOG.md, packages/astro-uxds/_content/releases.md, packages/astro-uxds/package-lock.json, packages/astro-uxds/package.json, packages/react/CHANGELOG.md, packages/react/package-lock.json, packages/react/package.json, packages/web-components/CHANGELOG.md, packages/web-components/package.json
=> Release 6.11.0

.changeset/quick-kings-tie.md, packages/web-components/src/global/_reset.scss
This was the OG link style update that was supposed to be in next, not main.
https://rocketcom.atlassian.net/browse/ASTRO-3167
=> Link style update

packages/astro-uxds/_content/_data/navigation.json, packages/astro-uxds/_content/components/tag.md, packages/astro-uxds/_content/design-guidelines/glossary.md, packages/web-components/src/stories/tag.stories.mdx
Updates astrouxds with tag documentation. 
- Adds new tag component page
- Adds tag page to navigation
- Adds tag page link to glossary
https://rocketcom.atlassian.net/browse/ASTRO-2133
Docs update
=> docs(astrouxds): added tag comp, updated nav and glossary'

packages/astro-uxds/_content/components/button.md
This is a clone of https://github.com/RocketCommunicationsInc/astro/pull/612 but just off of the next branch to resolve conflicts.
=> docs(astro-uxds): updated button page

.changeset/few-candles-pull.md, packages/angular/CHANGELOG.md, packages/angular/package-lock.json, packages/angular/package.json, packages/angular/src/directives/proxies.ts, packages/astro-uxds/CHANGELOG.md, packages/astro-uxds/_content/releases.md, packages/astro-uxds/package-lock.json, packages/astro-uxds/package.json, packages/react/CHANGELOG.md, packages/react/package-lock.json, packages/react/package.json, packages/web-components/CHANGELOG.md, packages/web-components/package-lock.json, packages/web-components/package.json
=> Release 6.12.0

packages/astro-uxds/_content/components/global-status-bar.md
Updated text in global status bar page. No images added. Compliance not updated 
(https://rocketcom.atlassian.net/browse/ASTRO-4045)
=> Astro 4045 global status bar page update

packages/astro-uxds/_content/components/radio-button.md
Updated radio buttons page "rules of thumb" text
(https://rocketcom.atlassian.net/browse/ASTRO-4046)
=> Astro 4046 update radio buttons page

packages/astro-uxds/_content/components/clock.md, packages/astro-uxds/_content/design-guidelines/theme.md, packages/web-components/package-lock.json
Updated theme page text under "Implementations"
(https://rocketcom.atlassian.net/browse/ASTRO-3924)
=> docs(astro-uxds): updated implementation text on theme page

README.md
Fix incorrect wording in README.  Changed ~remove~ to "see".
Change is needed to have wording make sense.
=> Update README with correct wording

packages/astro-uxds/_content/components/clock.md
Updated text on clock appearance and behavior section
(https://rocketcom.atlassian.net/browse/ASTRO-1968)
=> (document): updated clock appearance and behavior text

packages/web-components/package-lock.json, packages/web-components/package.json, packages/web-components/src/components/rux-card/rux-card.scss
Updates design tokens@beta.11. Renames component dialog shadow token to a system token.
_changes like this would never be needed if we had component tokens._ 
ASTRO-4089
=> feat: update tokens to beta.11

packages/astro-uxds/_content/design-guidelines/grid.md
Created new row in grid breakpoints, updated values in grid breakpoints, updated text. 
There is one line in the bottom note “Add appropriate labels for applicable components” on the design page that I reached out to Amalya for clarification if it should be there, she thinks it was a mistake. Waiting for Cole to respond back with a confirmation. For now, it is not added. 
https://rocketcom.atlassian.net/browse/ASTRO-4033
=> Mp 4033 grids page update

packages/astro-uxds/_content/components/application-state.md
Updated application state text on page as per instructions on design page stating "updated text in green". Reached out to Cole for clarification if that is all that needs to be changed, as his page is very different from the live page. Will update if necessary. 
https://rocketcom.atlassian.net/browse/ASTRO-4057
=> (documentation): updated application-state text

packages/astro-uxds/_content/patterns/data-visualization.md
Updated text in data visualization page
https://rocketcom.atlassian.net/browse/ASTRO-4053
=> Mp 4053 data visualization page

.changeset/sweet-chefs-end.md, packages/angular/CHANGELOG.md, packages/angular/package-lock.json, packages/angular/package.json, packages/astro-uxds/CHANGELOG.md, packages/astro-uxds/_content/releases.md, packages/astro-uxds/package-lock.json, packages/astro-uxds/package.json, packages/react/CHANGELOG.md, packages/react/package-lock.json, packages/react/package.json, packages/web-components/CHANGELOG.md, packages/web-components/package-lock.json, packages/web-components/package.json, packages/web-components/src/components.d.ts
=> chore: changeset version/build

.changeset/shiny-roses-perform.md, packages/astro-uxds/package-lock.json, packages/web-components/src/components/rux-input/rux-input.scss, packages/web-components/src/components/rux-input/rux-input.tsx, packages/web-components/src/components/rux-input/test/__snapshots__/rux-input.spec.tsx.snap, packages/web-components/src/components/rux-input/test/index.html
Refactored input of type="password" to use a normal <button> rather than <rux-button> and then formatted button to match astro design specs using design tokens.
[ASTRO-4344](https://rocketcom.atlassian.net/browse/ASTRO-4344)
Part of the Astro spacing and design token initiative!
=> Km 4434 refactor password input

packages/astro-uxds/_includes/_footer.njk
Removed ECX reference from footer
https://rocketcom.atlassian.net/browse/ASTRO-4362
=> (documentation): removed ECX from footer

CONTRIBUTING.md
Add chromium manual install steps for M1 users
=> chore(contributing): add chromium manual install steps for M1 users

.changeset/small-tigers-do.md, packages/web-components/src/components/rux-notification/rux-notification.scss, packages/web-components/src/components/rux-notification/test/index.html
Added design tokens and resized notification banners to be in line with Astro documentation.
[ASTRO-3854](https://rocketcom.atlassian.net/browse/ASTRO-3854)
Part of the Astro spacing initiative!
=> Km 3854 notification banner spacing

.changeset/small-tips-carry.md, .changeset/thin-flowers-carry.md, .changeset/young-apricots-grin.md, packages/angular/CHANGELOG.md, packages/angular/package.json, packages/angular/src/directives/proxies.ts, packages/astro-uxds/CHANGELOG.md, packages/astro-uxds/_content/releases.md, packages/astro-uxds/package.json, packages/react/CHANGELOG.md, packages/react/package.json, packages/web-components/CHANGELOG.md, packages/web-components/package.json, packages/web-components/src/components/rux-timeline/rux-time-region/readme.md
=> Release 6.13.0

.changeset/unlucky-lamps-sin.md, packages/web-components/src/components/rux-push-button/rux-push-button.scss, packages/web-components/src/components/rux-push-button/rux-push-button.tsx, packages/web-components/src/components/rux-push-button/test/index.html
Add spacing tokens to rux-push-button and align to Astro specifications.
[ASTRO-4475](https://rocketcom.atlassian.net/browse/ASTRO-4475)
Part of the Astro spacing design token initiative!
=> Km 4475 push button spacing tokens

packages/astro-uxds/_content/_data/navigation.json, packages/astro-uxds/_content/design-tokens/installation.md
adds an installation page for devs explaining how to use tokens
ASTRO-3994
It's still unclear to developers how to actually use our tokens. 
- @jonathantneal this will add a new page to astro dub dub
=> docs(astrouxds): token installation

packages/astro-uxds/_content/patterns/table.md
Updated text for this page as per Confluence document changes
=> Table pattern text changes

packages/astro-uxds/_content/components/accordion.md
Updated Accordion text for website based on Confluence page
=> Updated Accordion text for website

.changeset/few-jars-drum.md, .changeset/shaggy-kangaroos-call.md, packages/web-components/src/components/rux-classification-marking/rux-classification-marking.tsx, packages/web-components/src/components/rux-menu-item/rux-menu-item.scss
removes some deprecated parts and custom props still in next 
7.0 prep
=> Remove deprecations

packages/web-components/src/common/functional-components/FormFieldMessage/FormFieldMessage.tsx, packages/web-components/src/components.d.ts, packages/web-components/src/components/rux-checkbox/rux-checkbox.scss, packages/web-components/src/components/rux-checkbox/rux-checkbox.tsx, packages/web-components/src/components/rux-checkbox/test/__snapshots__/rux-checkbox.spec.tsx.snap, packages/web-components/src/components/rux-checkbox/test/index.html, packages/web-components/src/utils/utils.ts
This pr is to port the changes to fix some bugs, edit the css to use svgs, and adjust the markup on the checkbox component from main -> next
https://rocketcom.atlassian.net/browse/ASTRO-4573
This brings the next branch current with the main branch for the checkbox component
=> Bk 4573 update checkbox next

packages/web-components/src/stories/accordion-item.stories.mdx, packages/web-components/src/stories/accordion.stories.mdx
Added draft storybook items for tux-accordion and rux-accordion-item
[ASTRO-4507](https://rocketcom.atlassian.net/browse/ASTRO-4507)
Create Accordion Component in Code [ASTRO-2136](https://rocketcom.atlassian.net/browse/ASTRO-2136)
Added storybook stuff!
=> Fm km 4570 create storybook for accordion

packages/astro-uxds/_content/patterns/table.md
=> docs(astrouxds): removed header sections

packages/web-components/src/components/rux-accordion/test/index.html, packages/web-components/src/stories/accordion.stories.mdx
Added a story for truncated to the accordion storybook item
=> add story for truncated

CONTRIBUTING.md
=> docs: framework reloading

packages/astro-uxds/.eleventy.js, packages/astro-uxds/_content/migration.md, packages/astro-uxds/scss/base/_base.scss, packages/web-components/.prettierignore, packages/web-components/CHANGELOG.md, packages/web-components/CSS-Prop-Migration.md, packages/web-components/MIGRATION.md
=> draft - docs: migration guide

.changeset/unlucky-foxes-pretend.md, packages/web-components/.storybook/preview-head.html, packages/web-components/src/common/functional-components/FormFieldMessage/FormFieldMessage.tsx, packages/web-components/src/common/functional-components/FormFieldMessage/form-field-message.scss, packages/web-components/src/components/rux-checkbox-group/rux-checkbox-group.scss, packages/web-components/src/components/rux-checkbox/rux-checkbox.scss, packages/web-components/src/components/rux-checkbox/rux-checkbox.tsx, packages/web-components/src/components/rux-checkbox/test/__snapshots__/rux-checkbox.spec.tsx.snap, packages/web-components/src/components/rux-checkbox/test/index.html, packages/web-components/src/components/rux-clock/rux-clock.scss, packages/web-components/src/components/rux-input/rux-input.scss, packages/web-components/src/components/rux-notification/rux-notification.scss, packages/web-components/src/components/rux-push-button/rux-push-button.scss, packages/web-components/src/components/rux-radio-group/rux-radio-group.scss, packages/web-components/src/components/rux-segmented-button/rux-segmented-button.scss, packages/web-components/src/components/rux-select/rux-select.scss, packages/web-components/src/components/rux-textarea/rux-textarea.scss, packages/web-components/src/components/rux-tree-node/rux-tree-node.scss, packages/web-components/src/global/_variables.scss, packages/web-components/src/stories/notification.stories.mdx
* adds inline svg to form field
* adds inline svg to checkboxes
=> Light theme svgs

packages/astro-uxds/_content/design-guidelines/theme.md
=> docs: fix formatting on theme page

.changeset/rude-rabbits-boil.md, package-lock.json, packages/astro-uxds/package-lock.json, packages/web-components/src/components.d.ts, packages/web-components/src/components/rux-table/rux-table-cell/rux-table-cell.scss, packages/web-components/src/components/rux-table/rux-table-header-cell/rux-table-header-cell.scss, packages/web-components/src/components/rux-table/rux-table-header-row/rux-table-header-row.scss, packages/web-components/src/components/rux-table/rux-table-row/rux-table-row.scss, packages/web-components/src/components/rux-table/rux-table.scss, packages/web-components/src/components/rux-table/test/index.html
Adjusted rux-table and all sub components to fit astro 7.0 design specifications. Also added spacing tokens.
[ASTRO-4606](https://rocketcom.atlassian.net/browse/ASTRO-4606)
Part of the Astro 7.0 Spacing initiative!
=> rux-table - add spacing tokens and adjust to fit astro 7.0 design specs

packages/astro-uxds/_content/_data/tokens.js, packages/astro-uxds/_content/design-tokens/reference.njk, packages/astro-uxds/package-lock.json, packages/astro-uxds/package.json
adds typography tokens to the reference
I couldve written some function to output all these but dupe was faster.
=> docs: add typography tokens

packages/web-components/src/components/rux-slider/rux-slider.tsx, packages/web-components/src/components/rux-slider/test/__snapshots__/rux-slider.spec.tsx.snap
Tiny change to rux-slider to make styling on thumb movement work. :)
=> rux-slider fix

packages/astro-uxds/_content/patterns/forms-and-validation.md
I added updated text from Confluence page for Forms and Validation. I did not add Image captions since new images have not been added to the next site yet.
=> Updated Text (minus new Images and Image Captions)

packages/web-components/src/components/rux-dialog/rux-dialog.scss
Updates some token names on rux-dialog 
https://rocketcom.atlassian.net/browse/ASTRO-4632
=> style(dialog): updated token names

packages/astro-uxds/_content/components/accordion.md
=> docs: accordion page

packages/web-components/src/components/rux-timeline/rux-time-region/rux-time-region.scss
=> fix(timeline): restore region color

packages/astro-uxds/_content/design-guidelines/typography.md
=> docs: typography page

packages/astro-uxds/_content/design-tokens/reference.njk
=> docs: spacing/fontsize/lineheight token docs

packages/astro-uxds/_content/design-guidelines/color.md
=> docs: colors page

packages/web-components/src/common/functional-components/FormFieldMessage/form-field-message.scss, packages/web-components/src/components/rux-clock/rux-clock.scss, packages/web-components/src/components/rux-input/rux-input.scss, packages/web-components/src/components/rux-input/rux-input.tsx, packages/web-components/src/components/rux-input/test/__snapshots__/rux-input.spec.tsx.snap, packages/web-components/src/components/rux-tabs/rux-tab/rux-tab.scss
Updates some tokens, adds some missing tokens, centers the eye icon in a pw input.
=> style: update tokens, center pw icon in input

packages/astro-uxds/_content/getting-started/_readme.md, packages/astro-uxds/_content/migration.njk, packages/starter-kits/html-js-starter/index.html, packages/starter-kits/react-starter/public/index.html, packages/web-components/CHANGELOG.md, packages/web-components/README.md, packages/web-components/src/stories/astro-sandboxes/forms/html/index.html, packages/web-components/src/stories/astro-sandboxes/forms/svelte/basic/public/index.html, packages/web-components/src/stories/astro-sandboxes/forms/svelte/validation/public/index.html, packages/web-components/src/stories/astro-sandboxes/sign-in/index.html, packages/web-components/src/stories/astro-sandboxes/themes/ag-grid/index.html, packages/web-components/src/stories/astro-uxds/welcome/angular.stories.mdx, packages/web-components/src/stories/astro-uxds/welcome/javascript.stories.mdx, packages/web-components/src/stories/astro-uxds/welcome/react.stories.mdx, packages/web-components/src/stories/astro-uxds/welcome/svelte.stories.mdx, packages/web-components/src/stories/astro-uxds/welcome/vue.stories.mdx
adds removal of roboto mono to migration guide and changelog.
updates all references
=> docs: typography

packages/astro-uxds/_content/design-tokens/installation.md, packages/web-components/src/stories/astro-uxds/customization.stories.mdx, packages/web-components/src/stories/astro-uxds/welcome/angular.stories.mdx, packages/web-components/src/stories/astro-uxds/welcome/javascript.stories.mdx, packages/web-components/src/stories/astro-uxds/welcome/react.stories.mdx, packages/web-components/src/stories/astro-uxds/welcome/svelte.stories.mdx, packages/web-components/src/stories/astro-uxds/welcome/vue.stories.mdx, packages/web-components/src/stories/themes/tailwind.stories.mdx
=> docs: some more docs

packages/astro-uxds/_content/_data/meta.js, packages/astro-uxds/_content/releases.md
=> docs: releases page

.changeset/afraid-terms-hear.md, packages/web-components/tsconfig.json
=> fix: remove type defs

packages/web-components/src/stories/time-region.stories.mdx, packages/web-components/src/stories/timeline.stories.mdx
=> Fix typo in docs

.changeset/brown-cats-love.md, packages/web-components/package-lock.json, packages/web-components/package.json
Updates tokens@1.0.2 to fix an issue where the typography classes were using rems in the calc and failing on build for projects that use Css Minimizer Plugin
=> fix: update tokens@1.0.2

.changeset/afraid-jobs-own.md, .changeset/afraid-terms-hear.md, .changeset/brown-cats-love.md, packages/angular-workspace/CHANGELOG.md, packages/angular-workspace/package.json, packages/angular-workspace/projects/angular/CHANGELOG.md, packages/angular-workspace/projects/angular/package.json, packages/angular-workspace/projects/angular/src/directives/proxies-list.ts, packages/astro-uxds/CHANGELOG.md, packages/astro-uxds/package.json, packages/react/CHANGELOG.md, packages/react/package.json, packages/web-components/CHANGELOG.md, packages/web-components/package.json
=> release: changeset and build

packages/astro-uxds/_content/_data/navigation.json, packages/astro-uxds/_content/compliance/mil-std-1472.md
Cleans up the MIL-STD-1472 compliance.
https://rocketcom.atlassian.net/browse/ASTRO-4682
I double checked with Steve G about removing the H.
=> docs(astrouxds): removed the H from mil-std-1472 compliance

.changeset/polite-pianos-allow.md, .changeset/selfish-plants-study.md, .changeset/tidy-moons-suffer.md, packages/angular-workspace/projects/angular/CHANGELOG.md, packages/angular-workspace/projects/angular/package.json, packages/angular-workspace/projects/angular/src/directives/proxies-list.ts, packages/astro-uxds/CHANGELOG.md, packages/astro-uxds/_content/releases.md, packages/react/CHANGELOG.md, packages/react/package.json, packages/web-components/CHANGELOG.md, packages/web-components/package.json
=> release v7.0.2

packages/astro-uxds/_content/design-guidelines/color.md
The word "states" was repeated twice in the first paragraph.
=> Remove extra "states"

packages/astro-uxds/css/app.css, packages/astro-uxds/css/home.css, packages/astro-uxds/css/sidebar.css, packages/astro-uxds/css/variables.css, packages/astro-uxds/scss/components/_nav.scss, packages/astro-uxds/scss/home.scss
noticed a tiny color change needed to be made to mobile-nav header and properly centered home page footer social icons.
Sometimes letting the perfect be the enemy of the good.
=> minor color and size tweak

.changeset/few-buttons-fold.md, packages/web-components/src/global/_reset.scss
Fixes scrollbar colors in firefox. 
https://github.com/RocketCommunicationsInc/astro/issues/832
FF scrollbar consistency
=> style: firefox scrollbars

.changeset/few-buttons-fold.md, .changeset/light-teachers-fold.md, .changeset/witty-pears-explode.md, packages/angular-workspace/CHANGELOG.md, packages/angular-workspace/package-lock.json, packages/angular-workspace/package.json, packages/angular-workspace/projects/angular/CHANGELOG.md, packages/angular-workspace/projects/angular/package-lock.json, packages/angular-workspace/projects/angular/package.json, packages/angular-workspace/projects/angular/src/directives/proxies-list.ts, packages/angular-workspace/projects/angular/src/directives/proxies.ts, packages/astro-uxds/CHANGELOG.md, packages/astro-uxds/_content/releases.md, packages/astro-uxds/package-lock.json, packages/astro-uxds/package.json, packages/react/CHANGELOG.md, packages/react/package-lock.json, packages/react/package.json, packages/web-components/CHANGELOG.md, packages/web-components/package-lock.json, packages/web-components/package.json
=> release: 7.1.0

packages/astro-uxds/_content/components/tag.md
Made a couple of corrections to captions on Don't images' captions.
=> Corrections to Tags image captions

packages/web-components/src/stories/astro-uxds/welcome/angular.stories.mdx
=> docs: fix angular typos

packages/astro-uxds/_content/getting-started/designers.md
Removed the text related to Sketch. Added text related to MIL-STD-1472. Also linked a couple bits of text to pages, hopefully did that correctly.
=> Updated Getting Started as a Designer page

packages/astro-uxds/_content/community/propose-a-change.md, packages/astro-uxds/_includes/home.template.njk
Fix to typos on home page and propose a change page on astrouxds.com
[ASTRO-4776](https://rocketcom.atlassian.net/browse/ASTRO-4776)
=> fix two small typos

packages/astro-uxds/_content/components/tag.md
Updated the information on [AstroUXDS Tag Page](https://www.astrouxds.com/components/tag/)
[ASTRO-4769](https://rocketcom.atlassian.net/browse/ASTRO-4769)
Update AstroUXDS.com with the latest information!
=> Change Tag documentation on AstroUXDS.com

.changeset/violet-knives-attack.md, packages/web-components/src/components.d.ts
Altering the changeset frontmatter from 'major' to 'patch'.
=> changing changeset from 'major' to 'patch'

packages/web-components/.storybook/manager-head.html, packages/web-components/.storybook/preview-head.html
adds google analytics to storybook.
(cant use the plugin bc its using GA 4)
=> feat: storybook google analytics

packages/web-components/.storybook/main.js, packages/web-components/.storybook/manager.js, packages/web-components/package-lock.json, packages/web-components/package.json
=> docs: rm storybook addon

.changeset/angry-garlics-deliver.md, packages/web-components/src/components/rux-tabs/rux-tab/rux-tab.scss
Adds `cursor: pointer` to enabled tabs. 
https://rocketcom.atlassian.net/browse/ASTRO-4882
=> style(tabs): added cursor pointer to enabled tabs

.github/workflows/pull-request.yml
We were getting a bunch of deprecated warnings after our GA's finished. Turns out they were woefully out of date.
=> test(GA): bump actions version

packages/web-components/package-lock.json, packages/web-components/package.json, packages/web-components/src/components/rux-clock/rux-clock.scss, packages/web-components/src/components/rux-log/rux-log.scss, packages/web-components/src/components/rux-log/rux-log.tsx, packages/web-components/src/components/rux-push-button/rux-push-button.scss
implements token@1.1 for new light theme color adjustments. 
notification banner will be tackled in separate PR
=> feat: update light theme tokens

.changeset/angry-garlics-deliver.md, .changeset/chilled-goats-argue.md, .changeset/eighty-actors-behave.md, .changeset/flat-cups-sit.md, .changeset/heavy-kings-smell.md, .changeset/nasty-oranges-greet.md, .changeset/popular-ladybugs-jam.md, .changeset/tasty-horses-ring.md, .changeset/warm-rice-divide.md, packages/angular-workspace/CHANGELOG.md, packages/angular-workspace/package-lock.json, packages/angular-workspace/package.json, packages/angular-workspace/projects/angular/CHANGELOG.md, packages/angular-workspace/projects/angular/package-lock.json, packages/angular-workspace/projects/angular/package.json, packages/angular-workspace/projects/angular/src/directives/proxies-list.ts, packages/react/CHANGELOG.md, packages/react/package-lock.json, packages/react/package.json, packages/web-components/CHANGELOG.md, packages/web-components/package.json, packages/web-components/src/components/rux-status/readme.md
=> Release 7.3.0

packages/web-components/.prettierrc
Updates the Prettier Configuration to match the JSON formatting used throughout the rest of the repo.
=> Update Prettier Configuration to match JSON formatting of monorepo

packages/web-components/src/stories/notification.stories.mdx
https://github.com/RocketCommunicationsInc/astro/pull/973
=> docs(notification): cherry picking

.changeset/olive-maps-sniff.md, packages/web-components/src/components/rux-tabs/rux-tabs.tsx, packages/web-components/src/components/rux-tabs/test/tabs.spec.ts
Fixed an issue with tabs where dynamically adding and removing would not work. 
Steps to reproduce:
```
<rux-tabs id="tab-set-id-1">
<rux-tab id="tab-id-1">Tab 1 title</rux-tab>
<rux-tab id="tab-id-2">Tab 2 title</rux-tab>
<rux-tab id="tab-id-3">Tab 3 title</rux-tab>
</rux-tabs>
<rux-tab-panels aria-labelledby="tab-set-id-1">
<rux-tab-panel id="panel1" aria-labelledby="tab-id-1">Tab 1 HTML content</rux-tab-panel>
<rux-tab-panel id="panel2" aria-labelledby="tab-id-2">Tab 2 HTML content</rux-tab-panel>
<rux-tab-panel id="panel3" aria-labelledby="tab-id-3">Tab 3 HTML content</rux-tab-panel>
</rux-tab-panels>
<button id="butt">do stuff</button>
<button id="remove">remove stuff</button>
<script>
butt.addEventListener('click', () => {
const newTabEl = document.createElement('rux-tab') …
```
=> fix(tabs): dynamic fix

packages/web-components/package-lock.json, packages/web-components/package.json, packages/web-components/src/components.d.ts, packages/web-components/src/components/rux-radio-group/rux-radio-group.tsx, packages/web-components/src/components/rux-radio-group/test/radio-group.spec.ts, packages/web-components/src/components/rux-radio/rux-radio.tsx, packages/web-components/src/index.html
=> wip Mc radio experiment

.changeset/three-coats-itch.md
fixes changeset. major -> minor
=> changeset to minor

packages/web-components/src/stories/breadcrumb.stories.mdx
adds fine print for how to use in all the frameworks
=> docs: frameworks

.github/workflows/pull-request.yml, packages/web-components/package.json
=> ci: fix test

.github/workflows/pull-request.yml
=> ci/cd: add opened type

packages/web-components/src/stories/astro-uxds/customization.stories.mdx
=> docs: add warning about parts

.changeset/wild-zebras-begin.md, packages/web-components/package-lock.json, packages/web-components/package.json, packages/web-components/src/components/rux-breadcrumb/test/basic/index.html
=> tokens@1.5.0

.changeset/chatty-avocados-exist.md, .changeset/five-radios-smoke.md, .changeset/good-cups-jam.md, .changeset/healthy-poets-yawn.md, .changeset/stale-hotels-remain.md, .changeset/witty-jeans-grow.md, packages/angular-workspace/CHANGELOG.md, packages/angular-workspace/package-lock.json, packages/angular-workspace/package.json, packages/angular-workspace/projects/angular/CHANGELOG.md, packages/angular-workspace/projects/angular/package-lock.json, packages/angular-workspace/projects/angular/package.json, packages/angular-workspace/projects/angular/src/directives/proxies-list.ts, packages/angular-workspace/projects/angular/src/directives/proxies.ts, packages/react/CHANGELOG.md, packages/react/package-lock.json, packages/react/package.json, packages/web-components/CHANGELOG.md, packages/web-components/package-lock.json, packages/web-components/package.json, packages/web-components/src/components.d.ts, packages/web-components/src/components/rux-checkbox/readme.md, packages/web-components/src/components/rux-input/readme.md, packages/web-components/src/components/rux-select/readme.md, packages/web-components/src/components/rux-select/rux-select.tsx, packages/web-components/src/components/rux-select/test/select.spec.ts, packages/web-components/src/components/rux-textarea/readme.md, packages/web-components/src/components/rux-textarea/rux-textarea.tsx, packages/web-components/src/components/rux-textarea/test/textareas.spec.ts
=> Release 7.9.0

.changeset/serious-pans-sell.md, packages/web-components/src/components/rux-button/rux-button.tsx, packages/web-components/src/components/rux-button/test/button.spec.ts, packages/web-components/src/components/rux-tabs/test/basic/tabs.vrt.spec.ts
adds reflection to button 
ASTRO-5812
=> feat(button): prop reflection

.changeset/spicy-shoes-joke.md, packages/angular-workspace/CHANGELOG.md, packages/angular-workspace/package-lock.json, packages/angular-workspace/package.json, packages/angular-workspace/projects/angular/CHANGELOG.md, packages/angular-workspace/projects/angular/package-lock.json, packages/angular-workspace/projects/angular/package.json, packages/angular-workspace/projects/angular/src/directives/proxies-list.ts, packages/react/CHANGELOG.md, packages/react/package-lock.json, packages/react/package.json, packages/web-components/CHANGELOG.md, packages/web-components/package-lock.json, packages/web-components/package.json
=> Release 7.9.1

.changeset/healthy-falcons-count.md, packages/angular-workspace/CHANGELOG.md, packages/angular-workspace/package-lock.json, packages/angular-workspace/package.json, packages/angular-workspace/projects/angular/CHANGELOG.md, packages/angular-workspace/projects/angular/package-lock.json, packages/angular-workspace/projects/angular/package.json, packages/angular-workspace/projects/angular/src/directives/proxies-list.ts, packages/react/CHANGELOG.md, packages/react/package-lock.json, packages/react/package.json, packages/web-components/CHANGELOG.md, packages/web-components/package-lock.json, packages/web-components/package.json
=> Release 7.9.2

packages/web-components/src/stories/timeline.stories.mdx
Adds a real code example showing vertical scroll
5918
=> docs(timeline): add story for vertical scroll

.changeset/green-rules-knock.md, packages/angular-workspace/CHANGELOG.md, packages/angular-workspace/package-lock.json, packages/angular-workspace/package.json, packages/angular-workspace/projects/angular/CHANGELOG.md, packages/angular-workspace/projects/angular/package-lock.json, packages/angular-workspace/projects/angular/package.json, packages/angular-workspace/projects/angular/src/directives/proxies-list.ts, packages/react/CHANGELOG.md, packages/react/package-lock.json, packages/react/package.json, packages/web-components/CHANGELOG.md, packages/web-components/package-lock.json, packages/web-components/package.json
=> Release 7.9.3

.changeset/good-toes-think.md, .changeset/mighty-countries-know.md, .changeset/nine-fishes-carry.md, .changeset/serious-taxis-crash.md, .changeset/seven-pens-rhyme.md, packages/angular-workspace/CHANGELOG.md, packages/angular-workspace/package-lock.json, packages/angular-workspace/package.json, packages/angular-workspace/projects/angular/CHANGELOG.md, packages/angular-workspace/projects/angular/package-lock.json, packages/angular-workspace/projects/angular/package.json, packages/angular-workspace/projects/angular/src/directives/proxies.ts, packages/react/CHANGELOG.md, packages/react/package-lock.json, packages/react/package.json, packages/web-components/CHANGELOG.md, packages/web-components/package-lock.json, packages/web-components/package.json, packages/web-components/src/components/rux-card/readme.md, packages/web-components/src/components/rux-tabs/rux-tab/readme.md
=> release: 7.10.0

.changeset/silver-ducks-rhyme.md, .changeset/thick-ants-look.md, .changeset/yellow-experts-provide.md, packages/angular-workspace/CHANGELOG.md, packages/angular-workspace/package-lock.json, packages/angular-workspace/package.json, packages/angular-workspace/projects/angular/CHANGELOG.md, packages/angular-workspace/projects/angular/package-lock.json, packages/angular-workspace/projects/angular/package.json, packages/react/CHANGELOG.md, packages/react/package-lock.json, packages/react/package.json, packages/web-components/CHANGELOG.md, packages/web-components/package.json
=> release: 7.11.0

.changeset/stupid-crabs-pretend.md, packages/web-components/src/components/rux-button-group/rux-button-group.tsx, packages/web-components/src/stories/button-group.stories.mdx
deprecates button group
ASTRO-5894
=> feat(button-group: deprecate

packages/web-components/src/stories/frameworks/react.stories.mdx
DOCS FRIDAY boiiiiiiiiiii
Updates the react integration story to include: 
- Better slots documentation 
- Updated css import to clarify that you don't need it if not using light theme 
DOCS FRIDAY 
DOCS FRIDAY DOCS FRIDAY 
DOCS FRIDAY DOCS FRIDAY DOCS FRIDAY 
DOCS FRIDAY DOCS FRIDAY DOCS FRIDAY DOCS FRIDAY 
DOCS FRIDAY
=> Mj.docfri react update

packages/web-components/src/components/rux-accordion/rux-accordion-item/test/accordion-item.spec.ts, packages/web-components/src/components/rux-accordion/test/accordion.spec.ts
adds tests for reflection in accordion/accordion item
ASTRO-5812
=> test(accordion): reflection

packages/web-components/src/stories/themes/tailwind.stories.mdx
updates tailwind docs on how to use the new plugin import
=> docs: update tailwind docs

.changeset/heavy-horses-jump.md, .changeset/moody-hotels-hang.md, .changeset/popular-ties-sleep.md, packages/angular-workspace/CHANGELOG.md, packages/angular-workspace/package.json, packages/angular-workspace/projects/angular/CHANGELOG.md, packages/angular-workspace/projects/angular/package-lock.json, packages/angular-workspace/projects/angular/package.json, packages/framework-testing/astro-angular/package-lock.json, packages/framework-testing/astro-react/package-lock.json, packages/framework-testing/astro-vue/package-lock.json, packages/react/CHANGELOG.md, packages/react/package.json, packages/web-components/CHANGELOG.md, packages/web-components/package.json
7.13.0 release 
-   Added `content` CSS Shadow Part
-   Fixes `rows` prop not working correctly
=> Release 7.13.0

packages/web-components/package-lock.json, packages/web-components/package.json
=> chore: bump tokens

.changeset/three-flowers-grab.md, packages/web-components/src/components/rux-tree-node/rux-tree-node.tsx, packages/web-components/src/components/rux-tree-node/test/tree-node.spec.ts
https://github.com/RocketCommunicationsInc/astro/issues/1194
=> fix(tree-node): click handling

.changeset/forty-pillows-love.md, .changeset/three-flowers-grab.md, packages/angular-workspace/CHANGELOG.md, packages/angular-workspace/package-lock.json, packages/angular-workspace/package.json, packages/angular-workspace/projects/angular/CHANGELOG.md, packages/angular-workspace/projects/angular/package-lock.json, packages/angular-workspace/projects/angular/package.json, packages/framework-testing/astro-angular/package-lock.json, packages/framework-testing/astro-react/package-lock.json, packages/framework-testing/astro-vue/package-lock.json, packages/react/CHANGELOG.md, packages/react/package-lock.json, packages/react/package.json, packages/web-components/CHANGELOG.md, packages/web-components/package-lock.json, packages/web-components/package.json
=> Release 7.15.1

packages/web-components/src/components/rux-log/rux-log.tsx
Changes log's filtering to no longer be case sensitive. 
Kiley gets all credit for this, I'm just making the PR 
https://github.com/RocketCommunicationsInc/astro/issues/1203
=> fix(log): filtered data is no longer case sensitive

packages/web-components/src/stories/classification-marking.stories.mdx, packages/web-components/src/stories/log.stories.mdx, packages/web-components/src/stories/notification.stories.mdx, packages/web-components/src/stories/status.stories.mdx
clarify how to import status type
=> docs: clarify status type

.changeset/calm-scissors-smash.md, packages/web-components/src/components/rux-classification-marking/rux-classification-marking.scss
=> fix(classification-marking): added default padding

.changeset/hungry-horses-behave.md, packages/web-components/package-lock.json, packages/web-components/package.json
=> bump tokens

packages/web-components/src/stories/timeline.stories.mdx
Added a bit of css to the nested timeline codependent example to change the color of nested tracks then documented it in storybook on the story.
Had some questions in a meeting today about how that would be accomplished.
=> docs(timeline) update storybook nested timelines documentation

packages/web-components/src/stories/astro-sandboxes/forms/angular/basic-form/src/app/app.component.html, packages/web-components/src/stories/astro-sandboxes/forms/angular/basic-form/src/app/app.component.ts, packages/web-components/src/stories/astro-sandboxes/forms/html/index.html, packages/web-components/src/stories/astro-sandboxes/forms/react/basic/package.json, packages/web-components/src/stories/astro-sandboxes/forms/react/basic/src/App.js, packages/web-components/src/stories/astro-sandboxes/forms/vue/basic/src/App.vue, packages/web-components/src/stories/astro-sandboxes/forms/vue/basic/src/main.js
Adds multi-select to all form examples.
=> Mj.add multi select to sandboxes

.changeset/funny-hotels-hear.md, packages/angular-workspace/CHANGELOG.md, packages/angular-workspace/package-lock.json, packages/angular-workspace/package.json, packages/angular-workspace/projects/angular/CHANGELOG.md, packages/angular-workspace/projects/angular/package-lock.json, packages/angular-workspace/projects/angular/package.json, packages/react/CHANGELOG.md, packages/react/package-lock.json, packages/react/package.json, packages/web-components/CHANGELOG.md, packages/web-components/package-lock.json, packages/web-components/package.json
=> release: 7.19.1

.changeset/healthy-peaches-return.md, .changeset/rich-cherries-hunt.md, .changeset/thirty-shirts-itch.md, packages/angular-workspace/CHANGELOG.md, packages/angular-workspace/package-lock.json, packages/angular-workspace/package.json, packages/angular-workspace/projects/angular/CHANGELOG.md, packages/angular-workspace/projects/angular/package-lock.json, packages/angular-workspace/projects/angular/package.json, packages/react/CHANGELOG.md, packages/react/package-lock.json, packages/react/package.json, packages/web-components/CHANGELOG.md, packages/web-components/package.json, packages/web-components/src/components.d.ts, packages/web-components/src/components/rux-timeline/readme.md, packages/web-components/src/components/rux-timeline/rux-track/readme.md, packages/web-components/src/components/rux-timeline/rux-track/rux-track.tsx
=> Release v7.20.0

packages/web-components/src/components/rux-tooltip/test/tooltip.spec.ts
Fixes some flake in the tooltip test.
Fixes failing test.
=> test(tooltip): fix test flake

packages/web-components/src/components/rux-timeline/rux-timeline.tsx
=> Mj.timeline playhead error

.changeset/spicy-owls-cry.md, packages/angular-workspace/CHANGELOG.md, packages/angular-workspace/package.json, packages/angular-workspace/projects/angular/CHANGELOG.md, packages/angular-workspace/projects/angular/package.json, packages/angular-workspace/projects/angular/src/directives/proxies-list.ts, packages/react/CHANGELOG.md, packages/react/package.json, packages/web-components/CHANGELOG.md, packages/web-components/package.json
=> release: 7.22.0

.changeset/five-snails-call.md, packages/angular-workspace/CHANGELOG.md, packages/angular-workspace/package-lock.json, packages/angular-workspace/package.json, packages/angular-workspace/projects/angular/CHANGELOG.md, packages/angular-workspace/projects/angular/package-lock.json, packages/angular-workspace/projects/angular/package.json, packages/framework-testing/astro-angular/package-lock.json, packages/framework-testing/astro-react/package-lock.json, packages/framework-testing/astro-vue/package-lock.json, packages/react/CHANGELOG.md, packages/react/package-lock.json, packages/react/package.json, packages/web-components/CHANGELOG.md, packages/web-components/package-lock.json, packages/web-components/package.json
=> Release: 7.22.1

packages/web-components/src/stories/astro-sandboxes/themes/ag-grid/index.html, packages/web-components/src/stories/astro-sandboxes/themes/ag-grid/package.json, packages/web-components/src/stories/astro-sandboxes/themes/ag-grid/src/index.js
This PR makes an update to the AG-Grid sandbox link to reflect the new package changes.
=> chore: updating ag-grid code sandbox example

.changeset/mighty-emus-stare.md, packages/angular-workspace/package-lock.json, packages/angular-workspace/projects/angular/package-lock.json, packages/angular-workspace/projects/angular/src/directives/proxies-list.ts, packages/framework-testing/astro-angular/package-lock.json, packages/framework-testing/astro-react/package-lock.json, packages/framework-testing/astro-vue/package-lock.json, packages/react/package-lock.json
-   CSS fix for accordion-item for Chrome version 131.0.6778.70.
=> chore: build for release

packages/angular-workspace/CHANGELOG.md, packages/angular-workspace/package-lock.json, packages/angular-workspace/package.json, packages/angular-workspace/projects/angular/CHANGELOG.md, packages/angular-workspace/projects/angular/package-lock.json, packages/angular-workspace/projects/angular/package.json, packages/angular-workspace/projects/angular/src/directives/proxies-list.ts, packages/framework-testing/astro-angular/CHANGELOG.md, packages/framework-testing/astro-angular/package-lock.json, packages/framework-testing/astro-angular/package.json, packages/framework-testing/astro-react/CHANGELOG.md, packages/framework-testing/astro-react/package-lock.json, packages/framework-testing/astro-react/package.json, packages/framework-testing/astro-vue/CHANGELOG.md, packages/framework-testing/astro-vue/package-lock.json, packages/framework-testing/astro-vue/package.json, packages/react/CHANGELOG.md, packages/react/package-lock.json, packages/react/package.json, packages/web-components/CHANGELOG.md, packages/web-components/package-lock.json, packages/web-components/package.json
=> release-7.26.1
